# Blog posts. Each targets a real informational query. Where a post would need a
# specific local rule, fee or statistic, it teaches the reader how to check the
# current source rather than stating a number that may be wrong by next year.
# Author notes marked AUTHOR: are HTML comments and never render as text.

POSTS = [
{
 "slug":"how-much-does-junk-removal-cost-in-orlando","mt":'How Much Does Junk Removal Cost in Orlando?',"date":"2026-09-18",
 "title":"How Much Does Junk Removal Cost in Orlando? What Actually Drives the Price",
 "desc":"Junk removal is priced by truck volume, not by the item. Here is what moves the number up or down, and how to get a quote that does not change on the day.",
 "read":"6 min",
 "intro":[
  "Almost everyone asks the same first question, and almost every answer online dodges it. So here is the honest version: nobody can tell you what your job costs without knowing how much of a truck it fills.",
  "That is not evasion, it is how the industry prices. Understanding why makes it much easier to spot a quote that is going to change on the day."],
 "sections":[
  ("Volume, not item count","Junk removal is priced by the fraction of the truck your load fills. A quarter load, a half load, a full load. This is why a single sofa and twelve bags of clothing can cost about the same: they take up similar space.",
   "It also explains something that surprises people. Ten heavy boxes of books often cost less than one wardrobe, because the boxes stack and the wardrobe does not.",None),
  ("The four things that actually move the price","Volume is the base. Four things adjust it.",None,
   ["<strong>Weight.</strong> Concrete, tile, dirt and roofing shingles hit a truck's weight limit long before they fill its space. These are quoted by weight, not volume.",
    "<strong>Disposal surcharges.</strong> Some items cost money to dispose of regardless of size. Tires, mattresses, refrigerant appliances and electronics usually carry a fee at the facility, which gets passed through.",
    "<strong>Labor and access.</strong> Not stairs, which should be included. But a long carry from a back yard, a narrow gate, or an item that has to be dismantled before it will fit through a door all take time.",
    "<strong>Disassembly.</strong> Sheds, hot tubs, decking and playsets are demolition before they are hauling, and that is priced differently from carrying a finished item out of a room."]),
  ("What should already be included","Be suspicious of a quote that treats these as extras, because they are standard:",None,
   ["All labor and loading. You should not be lifting anything.",
    "Stairs and second or third floor carries.",
    "Disposal fees for ordinary household material.",
    "Sweeping up the space that was cleared."]),
  ("How to get a quote that does not change","Photos. Every time.",
   "A phone description of a garage is always optimistic, in good faith, by everyone. Photos of the actual pile take five minutes and turn a rough guess into a number that holds. If a company will not look at photos before quoting, that is worth noticing.",None),
  ("What to ask before you book","Four questions separate a straight operator from one that will surprise you:",None,
   ["Is the price you just gave me the price I pay, or an estimate?",
    "What is in the pile that you cannot take?",
    "Are stairs and the carry included?",
    "Where does the material actually go?"]),
 ],
 "takeaway":"Send photos, get a number before anything is loaded, and ask what in your pile cannot be taken. Those three steps eliminate almost every unpleasant surprise in this industry.",
 "related":["what-junk-removal-companies-will-not-take","where-does-your-junk-actually-go","garage-cleanout-in-a-weekend"],
},
{
 "slug":"what-junk-removal-companies-will-not-take","mt":'What Junk Removal Companies Will Not Take',"date":"2026-09-11",
 "title":"What Junk Removal Companies Will Not Take, and Where It Has to Go Instead",
 "desc":"Paint, fuel, propane, chemicals and asbestos cannot legally ride in a junk truck. Here is the full list and what to do with each one.",
 "read":"5 min",
 "intro":[
  "This is the part of the job that generates the most friction, and almost all of it is avoidable. A crew arrives, quotes the pile, and then has to explain that a third of it cannot legally go in the truck.",
  "None of this is a company being difficult. Hauling hazardous material without the right licensing is illegal, and the facilities we tip at will reject a load that contains it."],
 "sections":[
  ("The hard no list","These cannot go in a standard junk removal truck anywhere in Florida:",None,
   ["Liquid paint, stains, solvents and thinners","Gasoline, diesel, motor oil and other fuels","Propane tanks, including the small camping ones","Pesticides, herbicides and pool chemicals","Car and marine batteries","Asbestos-containing material","Medical waste and sharps","Ammunition, flares and explosives","Anything actively leaking or of unknown contents"]),
  ("Where each one actually goes","Household hazardous waste is the answer for most of this list. Orange and Osceola counties both run collection programs for residents, and they are typically free for household quantities.",
   "Paint is the common exception with an easy fix. Fully dried or empty cans are no longer hazardous and can go with ordinary debris. Small amounts dry out quickly if you stir in cat litter or sawdust and leave the lid off. A gallon of liquid paint is a problem. A gallon of solid paint is a can.",None),
  ("Propane is the one people forget","Small green camping cylinders end up in garage cleanouts constantly and they are genuinely dangerous in a compactor. Larger grill tanks can usually be exchanged or returned at a retailer that sells them. Neither belongs in a truck full of furniture.",None,None),
  ("Asbestos: the one worth taking seriously","If your house was built before about 1980, asbestos may be present in floor tile and the adhesive under it, pipe insulation, ceiling texture, and some siding and roofing.",
   "Intact and undisturbed, it is generally not a hazard. Broken, cut or torn out, it is. It needs testing first, and if positive, a licensed abatement contractor. Any hauler who offers to just take it is putting their crew and your household at risk, and you should not let them.",None),
  ("The grey areas worth asking about","These are usually fine but tell the company up front, because they carry facility fees or handling requirements:",None,
   ["Tires. Usually accepted, almost always with a per-tire fee. Give a count when you book.",
    "Refrigerators, freezers and AC units. Fine, but refrigerant has to be recovered by a certified recycler first.",
    "Electronics and CRT televisions. Accepted, routed to e-waste rather than landfill.",
    "Mattresses with bed bugs. Say so in advance. It changes the handling, not the answer."]),
 ],
 "takeaway":"Walk your pile before the truck arrives and pull out anything liquid, pressurised, chemical or from a pre-1980 renovation. Twenty minutes of sorting prevents the most common bad surprise on the day.",
 "related":["how-much-does-junk-removal-cost-in-orlando","garage-cleanout-in-a-weekend","where-does-your-junk-actually-go"],
},
{
 "slug":"hurricane-debris-cleanup-central-florida","mt":'Hurricane Debris Cleanup in Central Florida',"date":"2026-09-04",
 "title":"Hurricane Debris Cleanup in Central Florida: What the County Takes and What It Does Not",
 "desc":"After a storm, county debris collection covers less than most people assume. Here is the split, and how to avoid waiting weeks for a pickup that was never coming.",
 "read":"6 min",
 "intro":[
  "After a named storm, Central Florida counties usually run a special debris collection. It is genuinely useful and it is also narrower than people expect, which is how a pile sits at a curb for three weeks before somebody realises it was never on the list.",
  "The distinction that matters is between storm-generated debris and everything else."],
 "sections":[
  ("What county storm collection generally covers","Post-storm passes are typically limited to debris the storm itself created, separated into categories:",None,
   ["Vegetative debris: limbs, branches, palm fronds, trunks","Construction and demolition debris from storm damage: fence sections, roofing, siding, drywall from flooding",
    "Sometimes white goods: appliances ruined by flooding, handled separately because of refrigerant",
    "Sometimes household hazardous waste, also separated"]),
  ("What it does not cover","This is where people get caught. Normal household junk that happened to be put out at the same time is not storm debris, and crews will drive past it.",
   "Furniture from a garage that did not flood, an old mattress, construction debris from a renovation that predates the storm, and anything in bags or boxes generally does not qualify. Several counties explicitly exclude bagged material because crews use grapple trucks that cannot handle bags.",None),
  ("Separate your piles or lose the pickup","The single most common mistake is one mixed pile. Grapple trucks make separate passes for separate categories. A pile of branches with a sofa in the middle of it is not a vegetative pile any more, and it may get skipped entirely on every pass.",
   "Keep vegetative separate from construction debris, keep appliances separate, keep hazardous separate, and keep it all out of the road and away from meters, hydrants and low lines.",None),
  ("How long it actually takes","First passes in hard-hit areas often run weeks after the storm, and a full sweep can take a month or more. If you can live with the pile, waiting is free and is genuinely the right call for a big vegetative pile.",
   "Hiring a hauler makes sense for the things the county will not take, for anything that is a hazard or a mosquito breeding site where it sits, and for rentals and businesses that cannot wait.",None),
  ("Before the next storm","The cheapest debris cleanup is the one you avoid. Clearing a garage of what you were going to get rid of anyway means less to become debris, and it means the garage can hold the patio furniture when the next warning comes.",None,None),
 ],
 "takeaway":"Separate your piles by category, keep bagged and boxed material out of them, and understand that anything not created by the storm is yours to handle. Check your own county's current guidance after every storm, because the rules and the categories change per event.",
 "related":["what-junk-removal-companies-will-not-take","garage-cleanout-in-a-weekend","shed-and-fence-removal-after-a-storm"],
},
{
 "slug":"where-does-your-junk-actually-go","mt":'Where Does Your Junk Actually Go?',"date":"2026-08-28",
 "title":"Where Does Your Junk Actually Go? Donation, Recycling and Landfill in Central Florida",
 "desc":"Every hauler says they donate and recycle. Here is what actually happens to each category of material, and the questions that tell you whether a company means it.",
 "read":"5 min",
 "intro":[
  "Every junk removal company on earth says it donates and recycles. It is the easiest claim in the industry to make and one of the easier ones to check.",
  "Here is what genuinely happens to each category, and what to ask if you want to know whether a company is actually doing it."],
 "sections":[
  ("Metal is the easy one","Appliances, bed frames, filing cabinets, fencing, mowers and general scrap are mostly steel. Steel has real scrap value, so recycling it is both better environmentally and cheaper than landfilling it.",
   "If a company tells you metal goes to the landfill, they are either lying or losing money on purpose.",None),
  ("Furniture depends entirely on condition","This is where claims get soft. Donation partners are charities running thrift operations, not disposal services. They can only take furniture they can sell.",
   "Clean, structurally sound, no rips, no heavy staining, no smoke damage, no pests. A sofa that has been in a damp garage for three years will be refused, and a hauler who promises it will be donated is telling you what you want to hear.",None),
  ("Mattresses are more recyclable than people think","A mattress separates into steel springs, foam and fibre, all of which have a downstream use. A dry, clean mattress can be genuinely recycled.",
   "A soaked, mouldy or infested one cannot, and will be landfilled. This is another reason not to leave one at a curb in Florida through an afternoon thunderstorm.",None),
  ("Electronics have their own stream","Televisions, monitors and computers contain both recoverable material and things you do not want in a landfill. CRT televisions in particular contain leaded glass. These go to e-waste processors, not general waste.",None,None),
  ("Cardboard, paper and yard waste","Flattened cardboard from a move is clean recyclable material and one of the better outcomes in the whole business. Yard waste is typically composted or mulched rather than landfilled.",None,None),
  ("The questions that separate claim from practice","If this matters to you, ask directly:",None,
   ["Which donation partners do you actually use? A real answer names organisations.",
    "Can you get me a donation receipt? A company genuinely donating can.",
    "What percentage of a typical load ends up in the landfill? An honest answer is a range, not zero.",
    "What happens to my refrigerator's refrigerant? The answer should involve a certified recycler."]),
 ],
 "takeaway":"Metal and cardboard are recycled because it is economically sensible. Furniture donation depends on condition, and any company promising to donate a damaged sofa is not being straight with you.",
 "related":["how-much-does-junk-removal-cost-in-orlando","what-junk-removal-companies-will-not-take","mattress-disposal-in-orlando"],
},
{
 "slug":"mattress-disposal-in-orlando","mt":'Mattress Disposal in Orlando',"date":"2026-08-21",
 "title":"Mattress Disposal in Orlando: Why the Curb Is Not an Option",
 "desc":"Standard trash will not take a mattress, HOAs cite you for leaving one out, and Florida rain ruins it within hours. Here are the options that actually work.",
 "read":"4 min",
 "intro":[
  "The mattress is the classic stuck item. It is too big for regular collection, too awkward for a car, and it is the single most cited item in HOA and code enforcement complaints about curbside junk.",
  "There are four real options and one that does not work."],
 "sections":[
  ("Why the curb fails","Three reasons, and they compound.","Standard residential trash collection will not take a mattress. In an HOA community or an incorporated city like Belle Isle, leaving one out can get you a violation notice. And a mattress left outside through one Florida afternoon storm absorbs an enormous amount of water, doubling in weight and ruling out recycling entirely.",None),
  ("Option one: bulk pickup, if your service offers it","Some residential waste services include a limited number of bulk item pickups per year, usually scheduled in advance with a specific item limit.",
   "Check your provider's current terms directly rather than relying on what a neighbour told you, because these programs change and they vary between municipalities in this area.",None),
  ("Option two: take it to a transfer station yourself","Possible if you have a truck and a free morning. Expect a disposal fee specifically for mattresses at most facilities, and check the hours and what they accept before you drive out with one strapped to a roof.",None,None),
  ("Option three: retailer haul-away on delivery","If the mattress is being replaced, the retailer will often take the old one when they deliver the new one, sometimes free and sometimes for a fee.",
   "This is the cheapest option by a distance and the one people most often forget to ask about. Ask before you buy, not after delivery is scheduled.",None),
  ("Option four: a hauler","Worth it when the mattress is not being replaced, when there are several, when it is upstairs, or when it needs to go today. A hauler takes it from the bedroom rather than the curb, which is the actual hard part of the job.",None,None),
  ("If there are bed bugs, say so","Not disclosing this is a genuine problem. An infested mattress carried unwrapped through a house and loaded into a truck with other people's furniture spreads the problem.",
   "Tell whoever is taking it. It changes how the item is bagged and handled and where it can go. It does not usually change whether they will take it.",None),
 ],
 "takeaway":"If you are buying a replacement, ask the retailer to haul the old one on delivery. It is almost always the cheapest route and it is the one most people miss.",
 "related":["where-does-your-junk-actually-go","how-much-does-junk-removal-cost-in-orlando","rental-turnover-cleanouts"],
},
{
 "slug":"garage-cleanout-in-a-weekend","mt":'Garage Cleanout in a Weekend: A Plan',"date":"2026-08-14",
 "title":"Garage Cleanout in a Weekend: A Plan That Actually Finishes",
 "desc":"Most garage cleanouts stall because of sorting, not lifting. Here is a two-day plan built around that, including what to pull out before a hauler arrives.",
 "read":"6 min",
 "intro":[
  "Garage cleanouts fail for a predictable reason. People start by opening boxes, get absorbed in the contents, and four hours later the garage is worse than when they began because everything is now on the driveway.",
  "The fix is to decide the rule before you touch anything, then apply it without reopening the decision."],
 "sections":[
  ("Saturday morning: decide the rule first","Before anything moves, write down what earns a place in this garage. Vehicles, lawn equipment, tools you used in the last two years, holiday decorations, sports gear in active use.",
   "Everything else is leaving unless there is a specific reason it stays. Having the rule written down means you are applying a decision rather than making a hundred new ones.",None),
  ("Saturday: four zones, no fifth","Mark four areas with tape or boxes. Keep. Donate. Hazardous. Gone.",
   "There is no maybe pile. The maybe pile is where garage cleanouts go to die, because it gets put back in the garage at the end of the weekend and you have achieved nothing.",None),
  ("Saturday afternoon: pull the hazardous material out now","Do this before you book anyone, because no hauler can take it and finding out on the day wastes everyone's time. Into the hazardous zone:",None,
   ["Liquid paint, stain, solvent and thinner","Gasoline, oil and fuel cans","Propane tanks including small camping cylinders","Pesticides, herbicides and pool chemicals","Car batteries","Anything unlabelled or leaking"]),
  ("Saturday evening: dry out the paint","Small amounts of leftover paint can be turned into ordinary waste. Stir in cat litter or sawdust, leave the lid off overnight, and by morning it is solid. A solid can is just a can.",
   "Larger quantities are not worth the effort. Take them to household hazardous waste collection with the rest.",None),
  ("Sunday morning: photograph the Gone pile and book","Photos get you an accurate quote. A verbal description of a garage pile is optimistic every single time, from everybody, without exception.",
   "Take four or five shots from different angles, including anything unusually heavy or awkward, and send them with the quote request.",None),
  ("Sunday: the donation run","Do this yourself if you have a vehicle, because it is the part a hauler adds the least value to. Clean, working, sellable items only. A charity is not a disposal service and cannot take a broken exercise bike.",None,None),
  ("What to ask the hauler","Three things before they load:",None,
   ["Is that the final price or an estimate?",
    "Is there anything in this pile you cannot take?",
    "Do you sweep up?"]),
 ],
 "takeaway":"The lifting is not the hard part and it is the part you can pay someone to do. Sorting is the hard part, and the only way through it is deciding the rule before you start and refusing to build a maybe pile.",
 "related":["what-junk-removal-companies-will-not-take","how-much-does-junk-removal-cost-in-orlando","estate-cleanout-checklist"],
},
{
 "slug":"estate-cleanout-checklist","mt":'Estate Cleanout Checklist',"date":"2026-08-07",
 "title":"Estate Cleanout Checklist: Clearing a Home After a Loss",
 "desc":"A practical order of operations for emptying a family home, including what to find before anything is hauled and how to handle disagreement between family members.",
 "read":"7 min",
 "intro":[
  "Clearing a parent's house is not a junk removal problem with a sad backdrop. It is a family and legal process that happens to end with a truck.",
  "This is the order that causes the fewest regrets, from people who have been through it."],
 "sections":[
  ("Before anything moves: find the paperwork","Go through the house once looking only for documents. Nothing gets thrown out, donated or sold until this is done.",None,
   ["Will, trust documents and any letter of instruction","Deeds, titles for vehicles and boats","Insurance policies, including life and burial","Bank, investment and retirement statements","Tax returns for the last several years","Social Security and pension correspondence","Safe deposit box keys and any records of one","Military discharge papers, which affect burial benefits"]),
  ("Then the places people hide things","An older generation that kept cash and valuables at home hid them in predictable places. Check all of them before a single box leaves:",None,
   ["Inside books, especially a row of them on a shelf","Taped under drawers and inside drawer cavities","Freezer, and inside food containers in it","Coat and suit pockets, and inside shoes","Under mattresses and inside pillowcases","Medicine cabinets and toilet tanks","Behind picture frames and inside frame backing","Toolboxes, paint cans and coffee tins in the garage"]),
  ("Photographs before furniture","Photographs, letters and home video are the things families actually regret losing, and they are the least likely to look valuable to someone clearing a room quickly.",
   "Box every photograph and every piece of correspondence and set it aside. Sorting can happen later, somewhere else, when nobody is working to a deadline.",None),
  ("Let each person name a small number of items","Disagreement over possessions is usually about meaning rather than money. A structure that works: each person privately lists a small number of items that matter to them, then the lists are compared.",
   "Most of the time the lists barely overlap, because people want different things for different reasons. The few genuine conflicts can then be handled one at a time instead of as a general argument.",None),
  ("Get an appraisal before assuming anything is worthless","Two categories catch people out. Things assumed valuable that are not, like most mass-market china, most collectible plates and most furniture from the eighties.",
   "And things assumed worthless that are not: mid-century furniture, tools, certain costume jewellery, vinyl records, cameras and militaria. If a house has a lot of any of these, an appraiser costs far less than what gets thrown away without one.",None),
  ("Then, and only then, clear the house","Once documents, photographs, keepsakes and anything appraised are out, the rest is volume. This is the part to hand off.",
   "Expect multiple truckloads for a full house with a garage and attic. Ask for a donation receipt for what goes to charity, since it may matter for the estate's taxes.",None),
  ("What cannot be hauled","Older homes accumulate exactly the material no hauler can take. Expect to find and separately dispose of:",None,
   ["Paint, solvents and garage chemicals","Old fuel and propane cylinders","Pesticides, some of them long banned","Firearms and ammunition, which have their own legal process","Prescription medication, which goes to a pharmacy take-back","Asbestos material in a pre-1980 house, which needs testing first"]),
 ],
 "takeaway":"Documents first, then hiding places, then photographs, then keepsakes, then appraisal, then the truck. Doing it in that order is the difference between a hard week and a permanent regret.",
 "related":["garage-cleanout-in-a-weekend","what-junk-removal-companies-will-not-take","where-does-your-junk-actually-go"],
},
{
 "slug":"rental-turnover-cleanouts","mt":'Rental Turnover Cleanouts in Orlando',"date":"2026-07-31",
 "title":"Rental Turnover Cleanouts: Getting a Unit Guest-Ready on a Deadline",
 "desc":"A practical guide for landlords and property managers in Orlando, Kissimmee and St. Cloud on clearing a unit between tenants or guests without losing days.",
 "read":"5 min",
 "intro":[
  "A vacant unit costs money every day it stays vacant, and in the short-term rental corridor around Kissimmee the gap between guests can be hours rather than days.",
  "The operators who handle this well are not faster on the day. They are better organised before it."],
 "sections":[
  ("Long-term turnover versus short-term turnover","These are genuinely different jobs.",
   "A long-term tenant move-out leaves behind whatever they abandoned, and you usually have a few days. A short-term rental turnover is about replacing worn furniture and clearing damage inside a booking gap, often on a fixed clock with a guest arriving.",None),
  ("Know your abandoned property obligations","Before you dispose of anything a departed long-term tenant left, understand that Florida law sets out a process for handling personal property left behind after a tenancy ends, including notice requirements and waiting periods.",
   "This is not optional and it is not something a hauler can advise you on. Talk to your attorney or property management company about the correct procedure for your situation before you clear a unit. Getting it wrong is expensive in a way that dwarfs the cost of the cleanout.",None),
  ("Book before the tenant leaves, not after","The single biggest scheduling win. If you know the move-out date, book the clearout for the day after rather than calling once you have walked the unit and seen the mess.",
   "Same-day availability is real but not guaranteed, and a unit sitting for two days waiting on a truck costs more than the cleanout.",None),
  ("Photograph everything before it moves","For the security deposit, for an insurance claim, and for your own protection. Photograph the unit on arrival, before anything is touched.",
   "Then have whoever clears it photograph the empty unit when they finish. That pair of photo sets settles almost every dispute before it starts.",None),
  ("The items that come up every time","Turnover cleanouts are remarkably repetitive. Expect:",None,
   ["Mattresses, which almost always need replacing on a schedule anyway",
    "Sun-destroyed patio furniture, especially in vacation rentals",
    "Damaged case goods: dressers, nightstands, coffee tables",
    "Whatever is in the garage or storage closet, which the tenant never mentioned",
    "Abandoned food and cleaning chemicals, which need separating out"]),
  ("Coordinate delivery and removal in the right order","When furniture is being replaced, clear the old set before the new one arrives, not after.",
   "Getting this backwards leaves two sets of furniture in a property with nowhere to put either, and turns a two-hour job into a day. Give both the delivery window and the removal window to whoever is doing the removal.",None),
  ("If you run several properties, use one contact","Managers with multiple units get better scheduling by consolidating. One point of contact, addresses and access details in advance, photo confirmation per unit so you are not driving out to verify.",None,None),
 ],
 "takeaway":"Book before the tenant leaves, photograph before and after, sequence removal ahead of delivery, and get legal advice on abandoned property rather than guessing at the process.",
 "related":["mattress-disposal-in-orlando","how-much-does-junk-removal-cost-in-orlando","moving-out-of-a-lake-nona-apartment"],
},
{
 "slug":"moving-out-of-a-lake-nona-apartment","mt":'Moving Out of a Lake Nona Apartment',"date":"2026-07-24",
 "title":"Moving Out of a Lake Nona Apartment: What to Do With What Is Left",
 "desc":"Getting a deposit back means an empty unit, and Lake Nona's HOA and apartment rules make the curb a bad plan. Here is the sequence that works.",
 "read":"4 min",
 "intro":[
  "Every move ends with the same pile: furniture that will not fit the new place, a mattress not worth moving, and a mountain of flattened boxes.",
  "In Lake Nona that pile has nowhere obvious to go, because both the apartment complexes and the HOA communities have real rules about what can sit outside."],
 "sections":[
  ("The curb is not available here","Most Lake Nona communities restrict what can be left outside and for how long, and enforcement is genuinely active in a way it is not everywhere.",
   "Apartment dumpsters are for household trash. Putting a sofa beside one typically gets the cost of removing it billed to your unit, which comes out of the deposit you are trying to protect.",None),
  ("Start with what is actually worth something","Two weeks before the move, not two days. Anything sellable takes time to sell.",
   "After that window closes, switch from selling to donating. Holding a dresser for another week hoping for a buyer is how people end up with a full apartment on move-out day.",None),
  ("Donate what is clean and sound","Charities can take furniture they can sell: clean, structurally sound, no rips or heavy staining. They cannot take a water-damaged particleboard bookshelf, and asking them to absorb a disposal cost is not a donation.",
   "Several organisations in the Orlando area will collect larger furniture. Book that collection early, because the good ones schedule out.",None),
  ("Cardboard is its own problem","A one-bedroom move generates a startling volume of cardboard. Flattened, it compresses well and it is clean recyclable material.",
   "Check whether your complex has a dedicated cardboard recycling area before you assume it does. Many do, and a stack beside a dumpster that has one is a violation rather than a recycling attempt.",None),
  ("Book the last pass before your final walkthrough","Whatever is left after selling and donating needs to be gone before the walkthrough, not after.",
   "Schedule it for the morning of, or the day before. A hauler takes it from inside the unit, which is the whole point. You do not carry anything down to a curb that will not accept it anyway.",None),
 ],
 "takeaway":"Sell early, donate what is clean, recycle the cardboard properly, and have anything left taken from inside the unit before your final walkthrough rather than after.",
 "related":["rental-turnover-cleanouts","mattress-disposal-in-orlando","where-does-your-junk-actually-go"],
},
{
 "slug":"shed-and-fence-removal-after-a-storm","mt":'Shed and Fence Removal After a Storm',"date":"2026-07-17",
 "title":"Shed and Fence Removal After a Storm: What to Do First",
 "desc":"A damaged shed or downed fence is a safety and insurance problem before it is a cleanup problem. Here is the order that protects your claim.",
 "read":"5 min",
 "intro":[
  "Florida storms take out sheds and fences more than almost anything else, and the instinct afterwards is to start clearing immediately.",
  "Slow down for one afternoon. What you do in the first day affects whether your insurance pays for any of it."],
 "sections":[
  ("Photograph before you touch anything","This is the step people skip and regret. Photograph the damage from multiple angles, wide and close, before anything is moved.",
   "An adjuster cannot assess damage that has already been hauled away. If you clear first and claim second, you are relying on their goodwill and your description.",None),
  ("Call your insurer before you hire anyone","Ask two questions: is this covered, and do you need to inspect before removal?",
   "Some policies cover detached structures and fencing, some do not, and some require an inspection before debris is cleared. Find out which yours is before a truck arrives.",None),
  ("Make it safe, and stop there","There is a difference between making a site safe and clearing it. Safe means no exposed nails or sharp metal where people walk, nothing that will blow into a neighbour's property in the next storm, and no standing water collecting where mosquitoes will breed.",
   "Tarp it, tape it off, secure the loose pieces. Then leave the rest until you have the insurance answer.",None),
  ("Storm debris versus ordinary debris","If your county is running post-storm collection, storm-damaged fencing and shed material usually qualifies as construction and demolition debris, which is collected separately from vegetative debris.",
   "What does not qualify is everything that was inside the shed. Contents are ordinary household junk regardless of the storm, and mixing them into a debris pile can get the whole pile skipped.",None),
  ("The contents are usually the hazardous part","Sheds store exactly what cannot be hauled: fuel cans, pesticides, pool chemicals, old paint, propane cylinders.",
   "After a storm these are often damaged or leaking, which makes them more urgent and more dangerous. Separate them, do not let them sit in standing water, and take them to household hazardous waste collection.",None),
  ("Rebuild permits are a separate question","Removing a damaged accessory structure and building a new one are different from a permitting standpoint, and requirements vary between Orange County, Osceola County and incorporated cities like Belle Isle and St. Cloud.",
   "Check with your local building department before you commit to a rebuild. Nobody hauling debris can answer this for you.",None),
 ],
 "takeaway":"Photograph it, call your insurer, make it safe, and only then clear it. Reversing that order is how people end up paying out of pocket for damage that was covered.",
 "related":["hurricane-debris-cleanup-central-florida","what-junk-removal-companies-will-not-take","garage-cleanout-in-a-weekend"],
},
]
