# Service-area content. Each entry is written to be genuinely different from the
# others: different housing stock, different jobs, different questions. Thin
# near-duplicate location pages are what Google's helpful-content system demotes,
# so do not template these down to a name swap.

AREAS = [
{
 "slug":"lake-nona","name":"Lake Nona","drive":"Home base","zips":"32827, 32832",
 "blurb":"Junk removal in Lake Nona, from new-build move-in debris to apartment turnovers around Medical City.",
 "intro":[
  "We are based on Narcoossee Road, which puts our truck inside Lake Nona rather than driving in from across town. For most of 32827 and 32832 that means we can usually be at the curb the same day you call.",
  "Lake Nona is the newest housing stock in Orlando, and that shapes the work. Most of what we haul here is not decades of accumulation. It is move-in debris: flattened wardrobe boxes stacked to the garage ceiling, packing foam, the old sectional that did not survive the move, and whatever the builder left in the garage.",
  "The other half is the rental side. The apartments and townhomes around Medical City turn over constantly, and a unit has to be empty before the next lease starts. We work to that deadline."],
 "hoods":["Laureate Park","Village Walk","Eagle Creek","Northlake Park","Storey Park","Isles of Lake Nona","Medical City"],
 "angle_h":"What Lake Nona actually calls us for",
 "angle":[
  ("New-build move-in debris","Boxes, foam, pallet wood, plastic wrap and the packaging from every appliance and piece of furniture that arrived at once. It fills a garage faster than people expect."),
  ("Apartment and townhome turnovers","Whatever the last tenant left, cleared and swept, on a date that works with the next lease."),
  ("Furniture that did not fit","The sectional that will not go up the stairwell, the dining set that is wrong for the new room, the mattress being replaced."),
  ("Office and clinic cleanouts","Medical City suites change hands. We take out the desks, chairs, casework and files.")],
 "faqs":[
  ("Do you do same-day junk removal in Lake Nona?","Usually, yes. We are based on Narcoossee Road, so there is no cross-town drive to get to 32827 or 32832. Call before noon and same afternoon is normally doable. Later in the day we will tell you honestly whether it is today or first thing tomorrow."),
  ("My HOA does not allow anything at the curb. Is that a problem?","No, and it is the most common question we get here. Most Lake Nona communities have rules about what can sit outside and for how long. We do not stage anything at the curb. We carry it from where it is straight into the truck and leave with it the same visit."),
  ("Can you get into Laureate Park and Village Walk with a truck?","Yes. The alleys and rear-loaded garages are tighter than a standard street, so we park where we can legally fit and carry from there. Tell us if you are on an alley-load lot and we will plan for it."),
  ("I have a garage full of flattened moving boxes. Do you take cardboard?","Yes, and cardboard is one of the better outcomes. It is clean recyclable material, so it goes to recycling rather than landfill. Volume is what sets the price, and flattened boxes compress well, which usually works in your favor."),
  ("Do you handle apartment turnovers near Medical City?","Yes. Give us the unit, the access details and the date the unit has to be clear. We work turnover deadlines regularly and we will send photos when the unit is empty."),
  ("Can you take the builder debris left in my new home?","Leftover trim, packaging, drywall offcuts and the like, yes. What we cannot take is anything hazardous: paint, solvents, fuel, propane or chemicals. Those need household hazardous waste drop-off."),
  ("Will you take the appliance packaging and the old appliance?","Both. The packaging is bulky but light. The appliance itself we take too, and if it still runs we try to route it to a donation partner rather than scrap it."),
  ("Do I need to be home?","No. Plenty of Lake Nona jobs are handled with a garage code or a photo of what goes. We confirm by text before we load and send photos when we are done."),
  ("Is there a trip fee for Lake Nona?","No. Lake Nona is our home base, so there is no trip charge anywhere in 32827 or 32832."),
  ("Can you do a second-floor or third-floor unit?","Yes. Stairs are part of the job and we do not charge extra for them. Tell us the floor when you call so we bring the right number of people.")],
 "nearby":["narcoossee","conway","belle-isle","st-cloud","kissimmee"],
},
{
 "slug":"narcoossee","name":"Narcoossee","drive":"About 10 minutes","zips":"32832, 34771",
 "blurb":"Junk removal in Narcoossee, including acreage properties, sheds, fencing and outbuildings.",
 "intro":[
  "Narcoossee is a short run down the road from us, and the work here looks different from the subdivisions north of it. Lots are bigger, a lot of properties have outbuildings, and the junk is often outside rather than in a garage.",
  "That means sheds that have collapsed or rotted, fence sections replaced after a storm, old above-ground pools, trailers, tractor parts and the general accumulation that happens when a property has room to accumulate.",
  "Long driveways and gates are normal here. Tell us about them when you call and we will bring the right truck and plan the approach instead of discovering it on arrival."],
 "hoods":["Live Oak Estates","Eagle Creek","Tyson Ranch","Isle of Pines","Narcoossee Road corridor","Split Oak area"],
 "angle_h":"What we haul in Narcoossee",
 "angle":[
  ("Sheds and outbuildings","Rotted, storm-damaged or simply unwanted. We can take them down and haul the material away in the same visit."),
  ("Fencing","Wood, vinyl and chain link, including posts. Storm replacement work generates a lot of this."),
  ("Above-ground pools and hot tubs","Drained, cut down and removed. The deck around it too if that is going."),
  ("Property and barn cleanouts","Years of stored equipment, feed bags, pallets, scrap metal and whatever has accumulated in a building nobody has opened in a while.")],
 "faqs":[
  ("Can you get down a long dirt or gravel driveway?","Usually yes. What stops us is soft ground after heavy rain and low tree limbs. Send a photo of the driveway when you call and we will tell you straight whether the truck makes it or whether we need to shuttle from a firmer spot."),
  ("Do you tear down sheds, or only haul them if they are already down?","We take them down. Wood and metal sheds are routine. If the shed has a concrete pad, tell us up front, because whether the pad goes changes the job significantly."),
  ("Is there a trip fee out to Narcoossee?","No. We are about ten minutes away on Narcoossee Road, so the same pricing applies as anywhere else we serve."),
  ("Can you remove old fencing including the posts?","Yes, including posts set in concrete. Post footings are slow work, so tell us roughly how many sections and whether the posts are concreted when you ask for a quote."),
  ("What about an above-ground pool?","Yes. It needs to be drained before we arrive, and we will cut it down and haul it. If there is a deck or surround going too, mention it, because that is often the larger half of the job."),
  ("Do you take scrap metal and old equipment?","Yes. Metal is one of the things we genuinely want, because it recycles cleanly. Old mowers, appliances, fencing, bed frames and general scrap are all fine."),
  ("I have a gate with a code. How does that work?","Give us the code or the gate contact when you book. Plenty of our Narcoossee jobs happen without the owner on site."),
  ("Can you handle a full barn or outbuilding cleanout?","Yes, and these are usually a multi-truck job. We would rather look at photos or walk it first and give you a real number than guess and surprise you."),
  ("What will you not take?","Paint, solvents, fuel, pesticides, propane tanks, asbestos and anything else classed as hazardous. On rural properties old fuel cans and pesticide containers come up often, so it is worth checking before we arrive."),
  ("Do you take yard debris and tree limbs?","Yes, cut to manageable lengths. Whole felled trees and stumps are a different trade and we will tell you if you need a tree service instead of us.")],
 "nearby":["lake-nona","st-cloud","kissimmee","conway","belle-isle"],
},
{
 "slug":"conway","name":"Conway","drive":"About 15 minutes","zips":"32806, 32812",
 "blurb":"Junk removal in Conway and the Lake Conway chain, including older homes, garages and estate cleanouts.",
 "intro":[
  "Conway is an older part of Orlando, and the housing reflects it. A lot of these homes went up between the 1950s and the 1970s, which means real garages, real attics, and families who have been in the same house long enough to fill both.",
  "The jobs here skew toward decades of accumulation rather than move-in debris: a garage nobody has parked in since the nineties, an attic full of boxes, a Florida room used as storage.",
  "Being on the Lake Conway chain also brings boat and dock material, and older streets with narrower driveways and mature trees, which we plan around."],
 "hoods":["Dover Shores","Pershing","Conway Estates","Lake Conway Estates","Gatlin","Anderson Park"],
 "angle_h":"What Conway calls us for",
 "angle":[
  ("Garage and attic cleanouts","Thirty years in one house fills a lot of space. We carry it down and out, you do not lift anything."),
  ("Estate cleanouts","When a long-held family home changes hands. We work slowly enough that nothing meaningful gets thrown out by mistake."),
  ("Boat, dock and lake gear","Old docks, boat covers, trailers, canoes, lifts and the rest of what collects on a lakefront property."),
  ("Furniture and appliances","Heavy old pieces out of houses with narrow hallways and tight stairs. This is exactly what we are for.")],
 "faqs":[
  ("Can you get a truck down a 1960s driveway?","Usually. Conway driveways are narrower than modern ones and the trees are mature, so if we cannot get the truck all the way in we park at the street and carry. That does not change your price."),
  ("Do you do attic cleanouts?","Yes, as long as there is safe floored access and a usable pull-down or stair. Our crew goes up and brings it down. If the attic is unfloored we will tell you before we start rather than put someone through a ceiling."),
  ("How do estate cleanouts work?","We go at your pace. Anything you want set aside gets set aside, and we point out anything that looks like it might matter rather than assuming. Usable furniture goes to donation where we can, and we can get you a donation receipt."),
  ("Can you remove an old dock or boat lift?","Dock material and lift components that are already out of the water, yes. Anything requiring in-water work or a marine contractor is outside what we do, and we will say so rather than take the job."),
  ("My house is from the sixties. Do you worry about asbestos?","We do, and you should too. Popcorn ceilings, old floor tile and certain pipe wrap from that era can contain asbestos. We do not disturb or haul suspected asbestos material. It needs testing and a licensed abatement contractor first."),
  ("Do you take old appliances from a garage?","Yes. Fridges, freezers, washers, dryers, water heaters and window units. Refrigerant appliances get handled through a recycler rather than dumped."),
  ("Can you take a piano?","Usually, and this comes up more in Conway than anywhere else we serve. Uprights are routine. Grands and anything going down stairs need a look first, so send a photo."),
  ("Is there a trip fee to Conway?","No. Conway is about fifteen minutes from our base and there is no trip charge."),
  ("What if I only have a couple of items?","That is fine and it is a common Conway call. Single-item and partial-load pricing exists precisely so you are not paying for a full truck to move one recliner."),
  ("Will you sweep up after?","Yes. We broom-sweep the space we cleared. A garage that has been full for twenty years will need more than a broom to look new, but you will not be cleaning up after us.")],
 "nearby":["belle-isle","lake-nona","narcoossee","kissimmee","st-cloud"],
},
{
 "slug":"belle-isle","name":"Belle Isle","drive":"About 18 minutes","zips":"32809, 32812",
 "blurb":"Junk removal in Belle Isle, serving the Lake Conway chain, Nela Isle and Venetian Gardens.",
 "intro":[
  "Belle Isle is its own incorporated city rather than part of unincorporated Orange County, which matters more than people expect. It has its own rules about what can sit at the curb and for how long, and enforcement is real because it is a small city where things get noticed.",
  "Our approach here is simple: nothing goes to the curb. We load from where the item sits and leave with it in the same visit, so there is no window where a pile is sitting outside your house.",
  "The lake frontage on the Conway chain also means the usual waterfront accumulation, and the streets around Nela Isle and Venetian Gardens are tight enough that we plan the park before we arrive."],
 "hoods":["Nela Isle","Venetian Gardens","Lake Conway shoreline","Hoffner Avenue corridor","Cornerstone area"],
 "angle_h":"What Belle Isle calls us for",
 "angle":[
  ("Same-visit removal with nothing left at the curb","The main reason people here call a hauler instead of waiting on a bulk pickup."),
  ("Lakefront and dock material","Old docks, covers, lifts, canoes, patio furniture and the rest of what a waterfront lot collects."),
  ("Garage and home cleanouts","Older homes, long ownership, full garages. Same story as neighboring Conway."),
  ("Furniture and appliance removal","Heavy items out of houses with narrow access, carried rather than dragged.")],
 "faqs":[
  ("Belle Isle has rules about curbside junk. How do you handle that?","By not using the curb at all. We carry everything from where it is directly into the truck and drive away with it. Nothing sits outside your house waiting for a pickup day, so there is nothing for the city to take issue with."),
  ("Should I check with the city before I book?","For a normal household removal, no, because nothing goes on public property. If a project involves demolition, a dumpster on the street or structural work, check with Belle Isle first, since those can carry permit requirements we cannot speak to on your behalf."),
  ("Can your truck handle the narrow streets around Nela Isle?","Yes, with a little planning. Some of those streets and driveways are tight, so we may park on the street and carry. Send a photo of the access if you are unsure and we will confirm before the day."),
  ("Do you take dock and waterfront material?","Yes, once it is out of the water. Decking, railings, covers, old lifts and shoreline junk. In-water removal needs a marine contractor, not us."),
  ("Is there a trip fee for Belle Isle?","No. It is roughly eighteen minutes from our base and pricing is the same as everywhere else we serve."),
  ("Can you do a whole-house cleanout?","Yes. Whole-house jobs usually take multiple truckloads, and we would rather walk it or see photos first and give you a real number than quote blind."),
  ("Do you take mattresses?","Yes. Mattresses are one of the worst things to leave at a curb and one of the more annoying things to dispose of yourself, which is why they are one of our most common single items."),
  ("What about paint and pool chemicals?","Neither, unfortunately. Paint, pool chemicals, solvents and fuel all need household hazardous waste drop-off. We will tell you what in your pile we cannot take before we start loading, not after."),
  ("Can you come on a Saturday?","Yes. We run Monday through Saturday, 7am to 7pm."),
  ("Do you give a price before you start?","Yes. You get the number before anything goes in the truck, and if the load ends up smaller than we estimated, the price comes down.")],
 "nearby":["conway","lake-nona","narcoossee","kissimmee","st-cloud"],
},
{
 "slug":"st-cloud","name":"St. Cloud","drive":"About 20 minutes","zips":"34769, 34771, 34772",
 "blurb":"Junk removal in St. Cloud, from historic downtown homes to new subdivisions and acreage off Canoe Creek.",
 "intro":[
  "St. Cloud has two distinct halves and we work both. There is the older core around New York Avenue and East Lake Tohopekaliga, where the houses are small, old and long-owned. Then there is everything that has gone up in the last decade toward Narcoossee and Canoe Creek, which is all new construction.",
  "The old half generates cleanouts: garages, sheds, attics, and estates as houses change hands. The new half generates move-in debris and the occasional builder leftover.",
  "Outside both, there is still real acreage in St. Cloud, which brings outbuildings, equipment and the kind of accumulation that only happens when a property has space."],
 "hoods":["Historic downtown / New York Ave","East Lake Toho","Canoe Creek","Hickory Tree","Narcoossee border","Nova Road area"],
 "angle_h":"What St. Cloud calls us for",
 "angle":[
  ("Garage, shed and property cleanouts","The older core generates decades of stored material. We clear it in one visit where we can."),
  ("Estate cleanouts","Long-held homes changing hands, worked carefully rather than fast."),
  ("New-build move-in debris","Boxes, packaging and builder leftovers from the newer subdivisions."),
  ("Acreage and outbuildings","Barns, workshops, equipment, scrap metal and whatever has accumulated out of sight.")],
 "faqs":[
  ("Do you charge extra to come out to St. Cloud?","No. St. Cloud is about twenty minutes from our base on Narcoossee Road and we do not add a trip fee."),
  ("Can you do same-day in St. Cloud?","Often, though less reliably than in Lake Nona simply because of the drive. Call early and we will tell you honestly whether it is today or tomorrow morning rather than promise and miss."),
  ("Do you take material from a historic downtown home?","Yes, with a caveat. Homes from that era can contain asbestos in floor tile, pipe wrap and ceiling texture, and lead paint on old trim. We do not disturb or haul suspected asbestos material. It needs testing and a licensed abatement contractor."),
  ("Can you clear a barn or workshop?","Yes. These are usually multiple loads. Send photos or let us walk it and you will get a real number instead of an optimistic one."),
  ("Do you take tractors, mowers and old equipment?","Yes, if we can move it. Anything seized, buried or too heavy for our crew and a winch needs equipment we do not carry, and we will tell you that before you book."),
  ("What about tires?","Usually yes, but tell us the count when you call. Tires carry a disposal fee almost everywhere and a large pile changes the price, so we would rather that be part of the quote than a surprise."),
  ("Can you handle a rental turnover?","Yes. Tell us the date the unit has to be clear and we will work to it. We send photos when the unit is empty."),
  ("Do you take fencing and yard debris?","Yes. Fence panels and posts, cut limbs and general yard waste. Whole trees and stumps need a tree service."),
  ("I am on acreage with a long driveway. Is that a problem?","Usually not, but soft ground after rain and low limbs are the two things that stop us. A photo of the driveway when you call saves everyone a wasted trip."),
  ("Do you donate anything?","Where we can. Usable furniture and working appliances go to local donation partners rather than the landfill, and we can get you a receipt if you want one.")],
 "nearby":["narcoossee","kissimmee","lake-nona","conway","belle-isle"],
},
{
 "slug":"kissimmee","name":"Kissimmee","drive":"About 25 minutes","zips":"34741, 34744, 34746, 34747",
 "blurb":"Junk removal in Kissimmee, including vacation rental turnovers and property manager accounts along the 192 corridor.",
 "intro":[
  "Kissimmee runs on short-term rentals, and that creates a kind of junk removal work that barely exists elsewhere in our area. Vacation homes replace furniture on a cycle, guests break things, and a unit has to be guest-ready between bookings with no gap.",
  "That means we schedule around check-out and check-in rather than around a normal workday, and we are used to property managers handling several properties at once.",
  "Outside the rental corridor, Kissimmee has plenty of ordinary residential work too: garages, estates, furniture and appliances in the older neighborhoods around Lake Tohopekaliga and downtown."],
 "hoods":["192 corridor","Old Town area","Celebration side","Buenaventura Lakes","Poinciana","Lake Tohopekaliga / downtown"],
 "angle_h":"What Kissimmee calls us for",
 "angle":[
  ("Vacation rental turnovers","Furniture swaps and clear-outs scheduled into the gap between guests, not whenever we happen to be free."),
  ("Property manager accounts","Several properties, one point of contact, photo confirmation on every job."),
  ("Bulk furniture replacement","When a rental gets refurnished, the old set has to leave the same day the new one lands."),
  ("Residential cleanouts","Garages, estates, appliances and furniture in the neighborhoods off the tourist corridor.")],
 "faqs":[
  ("Can you work around guest check-in and check-out?","Yes, and this is most of what we do in Kissimmee. Give us the window and we will work inside it. If the window is tight, tell us up front so we bring enough crew to finish inside it."),
  ("Do you work with property managers on multiple units?","Yes. One contact, several addresses, and photo confirmation for each unit so you can prove the job was done without driving out to look."),
  ("Can you do a furniture swap the same day the new furniture arrives?","Yes, and timing matters. Tell us when the delivery lands so we clear the old set before it, not after. Otherwise you have two sets of furniture in one house and nowhere to put either."),
  ("Is there a trip fee for Kissimmee?","No. Kissimmee is about twenty-five minutes out and pricing is the same as everywhere else we serve."),
  ("Do you take pool and patio furniture?","Yes. Sun-wrecked patio sets are one of the most common vacation rental items we haul."),
  ("Can you handle mattresses in bulk?","Yes. Rentals replace mattresses on a schedule and we are set up for volume. Tell us the count and sizes when you book."),
  ("What if the unit has a gate code or lockbox?","That is normal here. Give us the access details and we will handle it without anyone meeting us on site. Photos when we are done."),
  ("Do you take TVs and electronics?","Yes. Electronics go to an e-waste recycler rather than the landfill. Older tube TVs are heavy and awkward but we still take them."),
  ("Can you come on short notice if a guest leaves a mess?","We will try. Same-day out to Kissimmee is not guaranteed because of the drive, but tell us what happened and we will tell you the earliest we can realistically be there."),
  ("Do you take construction debris from a renovation?","Yes, within reason. Drywall, trim, flooring, cabinets and fixtures. What we do not take is hazardous material, and if the property is old enough to have asbestos flooring it needs testing first.")],
 "nearby":["st-cloud","narcoossee","lake-nona","belle-isle","conway"],
},
]
