# Service pages. Each targets a distinct search intent. The FAQs answer what
# people actually ask before booking that specific service, not generic filler.

SERVICES = [
{
 "slug":"furniture-removal","name":"Furniture Removal","h1":"Furniture Removal in Orlando",
 "blurb":"Sofas, sectionals, mattresses, dining sets and anything else too heavy or too awkward to move yourself.",
 "intro":[
  "Furniture is the single most common thing we haul, and it is the thing people most often try to handle themselves before calling. A sectional that came in through a sliding door in three pieces does not go out the front door in one.",
  "You do not lift anything. Point at it, we carry it out from wherever it sits, including upstairs, and we pad the doorways and corners on the way."],
 "takes":["Sofas, loveseats and sectionals","Mattresses and box springs","Dining tables and chairs","Dressers, wardrobes and armoires","Desks and office chairs","Recliners and sleeper sofas","Bed frames and headboards","Patio and outdoor furniture"],
 "faqs":[
  ("How much does it cost to remove a sofa?","Price is set by how much of the truck the item fills, not by the item's name. A single sofa is a partial load. You get the number before anything is loaded."),
  ("Do I have to move it to the curb?","No. That is the point of hiring us. We carry it from the room it is in, including a second or third floor, at no extra charge for stairs."),
  ("Will you damage my walls getting a sectional out?","We pad door frames and corners and we take pieces apart when that is the safer route. If something genuinely will not fit through the opening without damage, we stop and tell you before we force it."),
  ("Can you take a sleeper sofa? They are extremely heavy.","Yes. Sleeper sofas and recliners are heavier than they look because of the steel mechanism inside. We send enough crew rather than trying to hero it with two people."),
  ("Does my old furniture get donated?","Where it can be. Clean, structurally sound furniture goes to local donation partners. Anything stained, broken, smoke-damaged or infested will not be accepted by a charity, and we will be honest with you about which yours is."),
  ("Can you take just one chair?","Yes. Single items are normal work and priced as a partial load, not a full truck."),
  ("Do you take furniture from an apartment on the third floor?","Yes, and stairs do not cost extra. Tell us the floor when you book so we bring the right crew size."),
  ("What about a piano or a pool table?","Usually yes, but both need a look first. Send a photo and tell us whether stairs are involved and we will give you a straight answer before you book.")],
 "related":["mattress-removal","appliance-removal","estate-cleanout"],
},
{
 "slug":"appliance-removal","name":"Appliance Removal","h1":"Appliance Removal and Disposal in Orlando",
 "blurb":"Refrigerators, washers, dryers, water heaters and window units, disconnected where safe and recycled properly.",
 "intro":[
  "Appliances are heavy, awkward, and in Florida they are also a regulatory problem. Anything with refrigerant in it cannot legally go in a landfill without the refrigerant being recovered first, which is why a lot of places will not take your old fridge.",
  "We route refrigerant appliances through a recycler that handles that step, and metal appliances get recycled rather than dumped."],
 "takes":["Refrigerators and freezers","Washers and dryers","Dishwashers","Ovens, ranges and cooktops","Water heaters","Window and portable AC units","Microwaves","Small appliances in bulk"],
 "faqs":[
  ("Can you take a refrigerator?","Yes. Fridges and freezers contain refrigerant that has to be recovered by a certified recycler before the unit can be scrapped, and we route them accordingly instead of dumping them."),
  ("Do you disconnect the appliance?","We will unplug a unit and disconnect a simple water line. We do not disconnect hard-wired electrical or gas. Gas appliances need the gas line capped by a licensed plumber before we touch them, and we will not cut corners on that."),
  ("Will you take a water heater?","Yes. Drain it before we arrive if you can, because a full one holds forty or more gallons and is genuinely dangerous to carry."),
  ("Does the appliance get recycled or landfilled?","Metal appliances are mostly steel, which recycles cleanly and has real scrap value, so recycling is both better and cheaper than landfilling. Refrigerant units go through the recovery process first."),
  ("Can you take a working appliance to donation instead?","Yes, and tell us if it works, because it changes where it goes. Donation partners want working units and cannot use dead ones."),
  ("How much does appliance removal cost?","By volume, like everything else. A single appliance is a partial load. You get the number before we load."),
  ("Can you get a fridge out of a second-floor apartment?","Yes. Stairs are included. Tell us the floor when you book."),
  ("Do you take old tube TVs and electronics?","Yes. Electronics go to an e-waste recycler. Old CRT televisions are heavy and contain leaded glass, which is exactly why they should not go in a dumpster.")],
 "related":["furniture-removal","garage-cleanout","construction-debris-removal"],
},
{
 "slug":"mattress-removal","name":"Mattress Removal","h1":"Mattress Removal and Disposal in Orlando",
 "blurb":"Mattresses and box springs taken away the same visit, recycled where possible.",
 "intro":[
  "Mattresses are the item people most often discover they cannot get rid of. They are too big for a regular trash pickup, most transfer stations charge a separate fee for them, and a mattress left at a curb in Florida becomes a wet mattress very quickly.",
  "They are also one of the most recyclable things we handle. The steel, foam and fibre inside can be separated and reused, so a mattress that goes to a recycler mostly does not go to a landfill at all."],
 "takes":["Twin through California King mattresses","Box springs and foundations","Memory foam and hybrid mattresses","Futons and sofa bed mattresses","Crib mattresses","Bed frames and headboards","Multiple mattresses for rentals","Adjustable bed bases"],
 "faqs":[
  ("Why can't I just put a mattress on the curb?","In most places a standard trash service will not take one, and in an HOA or an incorporated city like Belle Isle leaving one out can get you a citation. It also soaks up rain within hours and becomes far heavier and far worse to handle."),
  ("Do mattresses get recycled?","Where a recycler will take them, yes. Steel springs, foam and fibre can all be separated and reused. A mattress that is soaked, mouldy or infested will be rejected by a recycler and has to be landfilled."),
  ("Will you take a mattress with bed bugs?","Tell us before we arrive. It changes how we bag and handle it and where it can go. What we cannot do is take an infested mattress through your house unwrapped and into a truck with other people's furniture, so honesty here protects everyone."),
  ("How much to remove one mattress?","A single mattress and box spring is a small partial load. You get the price up front."),
  ("Can you take several at once?","Yes. Rentals and property managers replace mattresses in batches and we are set up for it. Give us the count and sizes."),
  ("Do you take the frame too?","Yes. Metal frames, wooden slats and headboards all go in the same trip."),
  ("Do I need to move it outside first?","No. We take it from the bedroom, including upstairs."),
  ("Can you come the same day?","Usually in Lake Nona and nearby. Further out like Kissimmee it depends on the day's schedule, and we will tell you honestly rather than promise.")],
 "related":["furniture-removal","estate-cleanout","appliance-removal"],
},
{
 "slug":"garage-cleanout","name":"Garage Cleanout","h1":"Garage Cleanout Services in Orlando",
 "blurb":"Get the garage back. We clear it in one visit and sweep it out when we are done.",
 "intro":[
  "A garage cleanout is the job people put off longest, because the pile is intimidating and because sorting it feels like it has to happen before anything can move. It does not. We sort as we load.",
  "You tell us what stays. Everything else goes, and you get a swept floor and a garage you can actually park in at the end of the day."],
 "takes":["Boxes and stored household goods","Old furniture and appliances","Bikes, sports and exercise equipment","Lawn equipment and mowers","Scrap metal and old tools","Paint cans (empty and dried only)","Broken shelving and storage racks","Tires (tell us the count)"],
 "faqs":[
  ("How long does a garage cleanout take?","Most single-car garages are a couple of hours. A packed two-car garage with an attic above it can be a half day. We will give you a realistic window when we see it, not an optimistic one."),
  ("Do I need to sort everything first?","No. Point out what stays and we work around it. Most people find sorting is the reason the garage has stayed full for three years."),
  ("Can you take paint?","Only if it is fully dried out or the can is empty. Liquid paint is household hazardous waste and needs a proper drop-off. You can dry small amounts yourself with cat litter and then we can take the can."),
  ("What about old gasoline and propane tanks?","Neither. Fuel, propane, solvents and pesticides all need household hazardous waste disposal. We will point out anything in your pile we cannot take before we start, not after we have quoted you."),
  ("Do you sweep up?","Yes, broom-swept. A garage that has been packed for twenty years will need more than a broom to look new, but you will not be cleaning up after us."),
  ("Can you take the shelving and cabinets too?","Yes, including taking them off the wall. Tell us if they are going so we bring tools."),
  ("What happens to the usable stuff?","Working tools, bikes, sports equipment and furniture go to donation partners where they can. Metal goes to a recycler. What is genuinely finished goes to the landfill last, not first."),
  ("How much does a garage cleanout cost?","By how much of the truck it fills. A partial garage might be a half load, a full one might be more than a truck. You get the price before we load anything.")],
 "related":["estate-cleanout","storage-unit-cleanout","appliance-removal"],
},
{
 "slug":"estate-cleanout","name":"Estate Cleanout","h1":"Estate Cleanout Services in Orlando",
 "blurb":"Whole-house clearing handled carefully, at your pace, when a property has to be emptied.",
 "intro":[
  "Estate cleanouts are usually happening at a bad time. Somebody has died, or is moving into care, and the house has to be empty by a date that somebody else set. We try to make our part of it the easy part.",
  "We go at the speed you want. Anything you want to keep gets set aside, and if we come across something that looks like it might matter, documents, photographs, jewellery, we stop and show you rather than make the call ourselves."],
 "takes":["Whole-house contents","Furniture from every room","Appliances","Garage, attic and shed contents","Clothing and linens","Books, papers and files","Yard and patio items","Anything left after the family has taken what they want"],
 "faqs":[
  ("How does an estate cleanout work?","We walk the property with you first and agree what stays. Then we clear room by room. You do not have to be there for the whole thing, but most people want to be there at the start."),
  ("What if you find something valuable?","We stop and show you. We do not make judgement calls about what matters to your family. Documents, photographs, jewellery and anything that looks personal gets set aside for you to decide on."),
  ("Can you get me a donation receipt?","Yes. Usable furniture, working appliances, clothing and household goods go to local donation partners, and we can get you a receipt for what was donated."),
  ("How much does a whole-house cleanout cost?","It depends on the volume, and these are almost always multiple truckloads. We would rather walk it or see photos and give you a real number than quote blind and revise it upward on the day."),
  ("How fast can you do it?","A small house can be a day. A large one with a full garage and attic can be two or three. If you have a closing date or a landlord deadline, tell us and we will tell you honestly whether we can hit it."),
  ("Do I need to be there?","Not for the whole job. Plenty of estate cleanouts are handled by an out-of-state family member with a realtor or neighbour letting us in. We send photos throughout and when we finish."),
  ("Can you work with a realtor or an attorney?","Yes. We are used to working to a closing date and coordinating with whoever is managing the estate."),
  ("What will you not take?","Hazardous material: paint, solvents, fuel, pesticides, propane, ammunition and medical sharps. Older homes often have all of these in a garage. We will identify them and tell you where they need to go.")],
 "related":["garage-cleanout","furniture-removal","storage-unit-cleanout"],
},
{
 "slug":"hot-tub-removal","name":"Hot Tub Removal","h1":"Hot Tub Removal in Orlando",
 "blurb":"Drained, cut down and hauled away, including the surround and decking if that is going too.",
 "intro":[
  "A hot tub that has stopped being used becomes a problem fast in Florida. It holds water, it breeds mosquitoes, and it is far too heavy and too awkward for a couple of people and a pickup truck.",
  "We drain what is left, cut it into pieces we can carry, and haul the whole thing. If there is decking or a surround built around it, that can go in the same visit."],
 "takes":["Above-ground hot tubs and spas","Swim spas","Hot tub covers and lifters","Surrounding decking and steps","Above-ground pools","Pumps, heaters and equipment","Concrete pads (ask first)","Associated electrical housing (disconnected by an electrician first)"],
 "faqs":[
  ("Do I need to drain it first?","It helps a lot. A full hot tub holds hundreds of gallons and we cannot move it with water in it. If you cannot drain it, tell us and we will plan for it, but it adds time."),
  ("Do you disconnect the electrical?","No. Hot tubs are usually on a dedicated 240V circuit and that needs a licensed electrician to disconnect safely. Have that done before we arrive. We will not cut a live line."),
  ("Do you cut it up or take it whole?","Almost always cut up. A whole tub does not fit through a side gate and does not lift onto a truck without equipment. Cutting it down is faster, safer and cheaper than craning it out."),
  ("Can you take the deck around it?","Yes, and mention it when you ask for a quote because the deck is often the bigger half of the job."),
  ("What about the concrete pad underneath?","Sometimes. Concrete is extremely heavy and pricing works differently. Tell us the pad size and thickness and we will give you a separate number for it."),
  ("How long does it take?","Most straightforward above-ground tubs are a few hours once it is drained and disconnected. Add time for decking or difficult access."),
  ("Can you get it out through a narrow side gate?","That is exactly why we cut it down. Tell us the narrowest point on the route out and we will size the pieces to fit."),
  ("Do you remove in-ground spas?","That is demolition rather than removal and usually needs a contractor. We will tell you straight if your job is outside what we do.")],
 "related":["construction-debris-removal","shed-removal","garage-cleanout"],
},
{
 "slug":"construction-debris-removal","name":"Construction Debris Removal","h1":"Construction Debris Removal in Orlando",
 "blurb":"Renovation and build debris cleared without tying up a dumpster on the street for a week.",
 "intro":[
  "For a lot of renovation jobs a dumpster is the wrong tool. It sits in the driveway for a week, it may need a permit if it goes on the street, and you pay for it whether it is full or not.",
  "We come when the debris exists, load it, and leave. For contractors running several jobs, that usually works out cheaper and it keeps the site clear."],
 "takes":["Drywall and plaster","Lumber, trim and framing offcuts","Flooring: tile, carpet, laminate, hardwood","Cabinets and countertops","Fixtures, sinks and toilets","Roofing material (ask first)","Siding and fencing","Packaging, pallets and general site waste"],
 "faqs":[
  ("Is this cheaper than renting a dumpster?","Often, for small and mid-size jobs. A dumpster makes sense when debris accumulates over weeks. We make more sense when it arrives in bursts, because you only pay for what we actually haul."),
  ("Do you take concrete and brick?","In limited amounts. Heavy material is priced by weight rather than volume because it fills the truck's weight limit long before its space. Tell us roughly how much and we will give you a real number."),
  ("Can you handle a roof tear-off?","Ask us first. Shingles are heavy and quantity matters enormously. A small section is fine. A whole roof usually wants a dedicated dumpster."),
  ("What about asbestos?","We do not touch it. Pre-1980s flooring, pipe wrap, ceiling texture and some siding can contain asbestos. It needs testing and a licensed abatement contractor. Any hauler who offers to just take it is putting you and their crew at risk."),
  ("Do you work with contractors on ongoing jobs?","Yes. If you are running multiple sites, one contact and scheduled pickups usually works better than a dumpster per job."),
  ("Can you come same day mid-renovation?","Often, especially in Lake Nona and nearby. Tell us what you have and we will tell you the earliest we can realistically be there."),
  ("Do you sweep the site?","We broom-sweep the area we cleared. We are not a post-construction cleaning service, and we will say so rather than let you expect one."),
  ("What about paint, solvents and adhesives?","Not those. Liquid paint, solvents, adhesives and fuel are hazardous waste and need a proper drop-off, whatever the job.")],
 "related":["shed-removal","hot-tub-removal","appliance-removal"],
},
{
 "slug":"shed-removal","name":"Shed Removal and Demolition","h1":"Shed Removal and Demolition in Orlando",
 "blurb":"Rotted, storm-damaged or simply unwanted sheds taken down and hauled in one visit.",
 "intro":[
  "Florida is hard on sheds. Heat, humidity and storms take a wooden shed apart over a few years, and once the roof goes the rest follows fast. A shed that has reached that stage is not safe to disassemble casually.",
  "We take it down and haul the material in the same visit, including whatever has been stored inside it."],
 "takes":["Wood and metal sheds","Storm-damaged structures","Shed contents","Playsets and swing sets","Gazebos and pergolas","Fencing and posts","Above-ground pools","Concrete pads (ask first)"],
 "faqs":[
  ("Do you demolish the shed or only haul it?","We take it down. Wood and metal sheds of normal backyard size are routine work."),
  ("What about the concrete pad underneath?","Ask us separately. Concrete is heavy and priced differently from ordinary debris. Tell us the dimensions and thickness."),
  ("Can you clear out what is inside first?","Yes, and it is usually the same job. Sheds tend to be full of exactly the mix of old paint, fuel cans and pesticide we cannot take, so we will identify those before we start."),
  ("Is a permit needed to demolish a shed?","For a small accessory structure usually not, but it depends on your municipality, and Belle Isle and St. Cloud set their own rules. Check with your local building department. We will not tell you it is fine when we do not know."),
  ("How long does it take?","Most backyard sheds are a half day including the haul. Storm-damaged ones can be quicker to take apart but messier to clean up."),
  ("Can you get to a shed in a fenced back yard?","Usually. Tell us the width of the narrowest gate and we will size the pieces to fit through it."),
  ("Do you take playsets and swing sets?","Yes. Wooden playsets that kids have outgrown are one of our more common backyard jobs."),
  ("What about a shed with a rotted floor?","Tell us. A rotted floor makes it unsafe to walk on and changes how we take it apart, so we would rather know before we arrive.")],
 "related":["construction-debris-removal","hot-tub-removal","garage-cleanout"],
},
{
 "slug":"storage-unit-cleanout","name":"Storage Unit Cleanout","h1":"Storage Unit Cleanout in Orlando",
 "blurb":"Stop paying monthly for a unit you no longer want. We empty it and you close the account.",
 "intro":[
  "Storage units have a way of outliving their reason. People rent one during a move, then keep paying for years because emptying it means a weekend, a truck and somewhere to put everything.",
  "We clear it in one visit so you can hand the key back. Bring us the unit number and access details and you do not have to be there."],
 "takes":["Full unit contents","Furniture and mattresses","Boxes and stored household goods","Appliances","Business inventory and files","Sports and exercise equipment","Tools and equipment","Anything left after you take what you want"],
 "faqs":[
  ("Do I need to be at the unit?","No. Give us the facility, the unit number and the access code or gate details. We send photos when the unit is empty so you can close the account with confidence."),
  ("How much does it cost to clear a storage unit?","By volume. A 5x10 is usually well under a truckload. A 10x20 packed to the ceiling can be more than one. Photos get you a far more accurate number than a description."),
  ("Can you do it the same day I call?","Often, though it depends on the facility's access hours as much as our schedule. Some facilities restrict move-out times, so check yours."),
  ("Does anything get donated?","Yes, where it can be. Storage units are full of perfectly usable furniture and household goods, and that is a better outcome than a landfill."),
  ("What if I want to keep a few things?","Mark them or tell us which they are and we will set them aside. We can leave them at the unit or load them separately, whichever you prefer."),
  ("Can you clear a unit that has been auctioned or abandoned?","Yes, provided whoever is instructing us has the right to. We will need that confirmed by the facility or the lien holder before we touch anything."),
  ("Will you take business inventory and files?","Yes. If files need to be destroyed rather than dumped, tell us, because that needs a shredding service and we will point you to one rather than pretend otherwise."),
  ("Do you sweep the unit out?","Yes, broom-swept, which is what most facilities require before they will close your account without a cleaning fee.")],
 "related":["garage-cleanout","estate-cleanout","furniture-removal"],
},
]

SERVICES += [
{
 "slug":"house-cleanout","name":"House Cleanout","h1":"Whole House Cleanout in Orlando",
 "blurb":"Every room emptied, garage and attic included, on the deadline you are working to.",
 "intro":[
  "A whole-house cleanout is a different job from clearing a room. It is multiple truckloads, it usually has a closing date or a lease end attached to it, and the thing that goes wrong is almost always underestimating the garage and the attic.",
  "We walk the property first and give you a number for the whole thing, not a per-load guess that climbs all day."],
 "takes":["Furniture from every room","Appliances","Garage and attic contents","Shed and yard contents","Clothing, linens and household goods","Carpet and flooring being replaced","Boxes, papers and files","Whatever the family left behind"],
 "faqs":[
  ("How long does a whole house cleanout take?","A small two-bedroom is usually a day. A four-bedroom with a full garage and a floored attic can be two or three. If you have a closing date, tell us and we will say honestly whether we can hit it."),
  ("How much does it cost to clear a whole house?","Multiple truckloads, so the number depends entirely on volume. We would rather walk it or see photos of every room including the garage than quote from a description, because descriptions of garages are optimistic every single time."),
  ("Do I need to be there?","Not for the whole job. Plenty of these are run by an out-of-state owner with a realtor or neighbour letting us in. We send photos throughout and at the end."),
  ("Can you work to a closing date?","Yes, and book early. The week before a closing is the busiest week for this kind of work and availability tightens."),
  ("Do you take the carpet and flooring too?","Yes, if it is being replaced. Tear-out and haul in the same visit. Tell us the square footage so we size the truck."),
  ("What if the house is in bad condition?","Tell us before we arrive. Water damage, mould, pests or a property that has been sitting empty all change how we approach it and what protective equipment we bring."),
  ("Can you clear the garage and attic too?","Yes, and they are usually the biggest surprise in the job. Include them in the photos you send or the quote will be wrong."),
  ("Do you donate what is usable?","Yes. Clean, sound furniture and working appliances go to donation partners and we can get you a receipt, which may matter if this is an estate."),
  ("What cannot be taken?","Paint, solvents, fuel, propane, pesticides, ammunition and anything asbestos-containing in a pre-1980 house. We identify it and tell you where it goes rather than quietly leaving it.")],
 "related":["estate-cleanout","foreclosure-cleanout","garage-cleanout"],
},
{
 "slug":"foreclosure-cleanout","name":"Foreclosure Cleanout","h1":"Foreclosure Cleanout Services in Orlando",
 "blurb":"Bank-owned and pre-sale properties cleared and photo-documented, fast.",
 "intro":[
  "Foreclosure cleanouts run on other people's deadlines. An asset manager needs the property broom-clean and photographed before it can be listed, and every day it is not costs somebody money.",
  "We clear it, sweep it, and send a full photo set so you can close out the work order without driving to the property."],
 "takes":["Abandoned furniture and belongings","Appliances, working or not","Trash and debris throughout","Garage, shed and yard contents","Carpet and damaged flooring","Window coverings and fixtures","Exterior debris and overgrowth material","Anything left after the previous occupant"],
 "faqs":[
  ("How fast can you clear a foreclosure?","Most single-family properties are one day. Tell us the deadline when you book and we will confirm whether it is realistic rather than agreeing and missing it."),
  ("Do you provide photo documentation?","Yes, and it is standard on every foreclosure job. Before, during and after, by room. Most asset managers need it for the work order, so we send it without being asked."),
  ("Do you work with asset managers and REO agents?","Yes. One contact, multiple properties, consistent documentation on each. If you need a specific photo format or naming convention, tell us and we will match it."),
  ("What about personal property left behind?","This is the part to get right. Florida law sets out requirements for handling personal property left at a property, and those requirements depend on the legal posture of the case. Confirm with your attorney or servicer that the property is legally clear before we remove anything. We cannot make that determination for you."),
  ("Can you handle a property in poor condition?","Usually. Tell us up front if there is water damage, mould, pests or standing waste, because it changes the equipment and protection we bring. We would rather know than discover it."),
  ("Do you do exterior debris too?","Yes. Yard waste, dumped items, abandoned vehicles' contents and general exterior debris. Actual vehicles need a towing company."),
  ("Is the property left broom-clean?","Yes, swept throughout. Deep cleaning, carpet cleaning and painting are a different trade and we will say so rather than let you expect them."),
  ("How is it priced?","By volume like everything else, but photos matter more here because nobody has usually walked the property. Send whatever the inspection photos show and we will get close."),
  ("Can you be there on short notice?","Often. Foreclosure timelines move suddenly and we know it. Call and we will tell you the earliest we can realistically be on site.")],
 "related":["eviction-cleanout","house-cleanout","estate-cleanout"],
},
{
 "slug":"eviction-cleanout","name":"Eviction Cleanout","h1":"Eviction Cleanout Services in Orlando",
 "blurb":"Units cleared and documented after a tenant leaves, so you can turn the property.",
 "intro":[
  "An eviction cleanout is time-sensitive and it is also a legal process. The clearing part is straightforward. The part that catches landlords out is what can legally be done with what the tenant left.",
  "We do the clearing and the documentation. The legal question is one to settle with your attorney before we arrive, not after."],
 "takes":["Abandoned furniture and belongings","Appliances","Trash and debris","Garage and storage contents","Damaged carpet and flooring","Abandoned food and household chemicals","Yard and patio items","Anything left in the unit"],
 "faqs":[
  ("Can I just throw out what the tenant left?","Not necessarily, and this is the most important question on this page. Florida law sets out a process for personal property left behind after a tenancy ends, including notice and waiting periods, and it differs depending on how the tenancy ended. Get this confirmed by your attorney or property manager before anything is removed. Getting it wrong costs far more than the cleanout."),
  ("Do you photograph everything first?","Yes. Full photo set on arrival before anything moves, then again when the unit is empty. That protects you on the deposit, on an insurance claim and in any dispute."),
  ("How fast can you turn a unit?","Most apartments and small houses are same day once we are on site. Larger properties can be two days. Every vacant day costs you, so book as soon as you have a date."),
  ("Can you store the tenant's property instead of disposing of it?","We are a hauling company, not a storage facility. If your legal process requires storage, arrange a storage unit and we can move the property into it rather than dispose of it."),
  ("Do you handle units in bad condition?","Yes. Tell us in advance about pests, standing waste, mould or biohazard so we bring the right protection. Genuine biohazard needs a remediation company and we will tell you if that is what you have."),
  ("What about abandoned food and chemicals?","Common in these units and handled separately. Food waste goes as general waste, cleaning chemicals and anything hazardous needs proper disposal and we will identify it."),
  ("Do you work with property management companies?","Yes. Multiple units, one contact, photo documentation per unit so you are not driving out to verify each one."),
  ("Is the unit left ready to show?","It is left empty and swept. Paint, carpet cleaning and repairs are separate trades."),
  ("How much does it cost?","By volume. Send photos of the unit if you have walked it. If you have not, tell us the bedroom count and we will give you a range and confirm on arrival before loading.")],
 "related":["foreclosure-cleanout","house-cleanout","storage-unit-cleanout"],
},
{
 "slug":"hoarding-cleanout","name":"Hoarding Cleanout",
 "h1":"Hoarding Cleanout and Junk Removal in Orlando",
 "blurb":"Heavy-volume clearing handled without judgement, at a pace that works for the household.",
 "intro":[
  "Let us be straight about what we are and are not. We are a junk removal company. We handle the hauling side of a hoarding situation: the volume, the sorting, the carrying and the disposal, and we do it without making anyone feel judged.",
  "We are not a biohazard remediation company. If a property involves human or animal waste, decomposition, serious mould or a pest infestation, that needs a licensed remediation contractor before or alongside us, and we will tell you that rather than take the job and do it badly.",
  "For the large majority of heavy-accumulation properties, what is actually needed is people, trucks and patience. That we can do."],
 "takes":["Heavy accumulation throughout a property","Furniture buried under contents","Boxes, papers and bags in volume","Appliances and electronics","Expired food and packaging","Clothing and textiles in bulk","Yard and garage accumulation","Multiple truckloads over multiple days"],
 "faqs":[
  ("Do you handle hoarding situations?","We handle the hauling side: volume, sorting, carrying and disposal. What we do not do is biohazard remediation. If there is human or animal waste, decomposition, serious mould or an active infestation, that needs a licensed remediation contractor. We will tell you honestly which situation you have."),
  ("Will your crew judge the household?","No, and we take that seriously. Our crew works the job and does not comment. If the person living there is present, we follow their pace and their instructions about what gets looked at."),
  ("Can we go slowly, over several days?","Yes, and for most households that works far better than one overwhelming day. We can work in sessions, room by room, with breaks between."),
  ("What if the person changes their mind mid-job?","We stop. Nothing leaves without agreement. Forcing the pace damages trust and usually makes the overall situation worse, not better."),
  ("Do you look through things before disposing?","As much as you want us to. Some families want everything checked for documents and valuables, some want speed. Tell us which and we work that way."),
  ("How much does a hoarding cleanout cost?","It is volume work, usually many truckloads, so it is one of the larger jobs we do. We will not quote it without seeing it. A walkthrough costs you nothing and gets you a real number."),
  ("Can you work with a therapist or social worker?","Yes, and where one is involved it usually goes better. We take direction from whoever the family has coordinating."),
  ("Is it confidential?","Yes. Unmarked approach if you want it, no photos shared, no discussion of the property with anyone but you."),
  ("What about pests?","Tell us before we arrive. Light activity we can work around with the right protection. An active infestation needs pest control first, and we will say so.")],
 "related":["house-cleanout","estate-cleanout","garage-cleanout"],
},
{
 "slug":"office-cleanout","name":"Office and Commercial Cleanout",
 "h1":"Office and Commercial Cleanout in Orlando",
 "blurb":"Suites, retail units and warehouses cleared after hours so you are not disrupting business.",
 "intro":[
  "Commercial cleanouts run on lease dates and landlord requirements, and most of them need to happen when the business is closed.",
  "We work evenings and Saturdays, we bring enough crew to finish inside the window, and we leave the space in the condition the lease requires."],
 "takes":["Desks, workstations and cubicles","Office and conference chairs","Filing cabinets and storage","Computers, monitors and electronics","Retail fixtures and shelving","Break room appliances","Carpet and partition walls","Warehouse racking and pallets"],
 "faqs":[
  ("Can you work after hours or on weekends?","Yes, and most commercial jobs are scheduled that way. Tell us the window and we will size the crew to finish inside it."),
  ("Do you handle office furniture in volume?","Yes. Cubicle systems, desking and chairs in quantity are routine. Give us a rough count and a floor plan if you have one."),
  ("What happens to the electronics?","E-waste recycler, not landfill. If the machines held company data, that is a separate question. We do not perform certified data destruction, so have drives wiped or removed first, or use a certified ITAD provider."),
  ("Can you take retail fixtures and shelving?","Yes, including gondola shelving, display cases, racking and slatwall, and we will disassemble them."),
  ("Do you remove carpet and partitions?","Yes. Tear-out and haul. Anything structural or load-bearing needs a contractor, and older buildings may need asbestos testing before flooring comes up."),
  ("Do you provide a certificate of insurance?","Yes. Most commercial landlords and property managers require one before work starts, so ask early and give us the certificate holder details."),
  ("Can you meet a lease surrender deadline?","Yes, if you book with enough time. Tell us exactly what the lease requires the space returned as, because broom-clean and fully restored are very different jobs."),
  ("Do you work with property managers on multiple sites?","Yes. One contact, several locations, documentation per site."),
  ("How is commercial work priced?","By volume, same as residential, but access and timing matter more. Loading dock versus third floor with one elevator is a real difference and we would rather account for it up front.")],
 "related":["storage-unit-cleanout","construction-debris-removal","furniture-removal"],
},
{
 "slug":"yard-waste-removal","name":"Yard Waste Removal","h1":"Yard Waste and Debris Removal in Orlando",
 "blurb":"Branches, palm fronds, clippings and storm debris hauled without waiting on a county pass.",
 "intro":[
  "Florida yards generate debris faster than almost anywhere. Palms drop constantly, growth is year-round, and one storm can produce more material than a year of normal trimming.",
  "County storm collection is useful but it runs on its own schedule and only takes storm-generated material. When you need it gone now, or it is not storm debris, that is us."],
 "takes":["Branches and cut limbs","Palm fronds and trunks","Grass clippings and leaves","Hedge and shrub trimmings","Storm debris","Old mulch and sod","Landscape timbers and edging","Pots, planters and yard decor"],
 "faqs":[
  ("Do you cut the tree down or only haul it?","Haul only. We take material that is already cut to manageable lengths. Felling a standing tree and grinding stumps is a tree service, and we will tell you that rather than attempt it."),
  ("Can you take palm trunks?","Yes, cut into sections we can carry. Whole palm trunks are extremely heavy and dense, so tell us the count and rough size when you ask for a quote."),
  ("Is this cheaper than waiting for county pickup?","No, county pickup is free. If you can wait and your material qualifies, wait. We are for when it does not qualify, when you cannot wait, or when it needs to come from the back yard rather than the curb."),
  ("Do you take it from the back yard?","Yes. Getting it to the curb is the part most people want to avoid and it is included."),
  ("What happens to yard waste?","It is typically composted or mulched rather than landfilled, which is one of the better outcomes in this business."),
  ("Can you take old mulch and sod?","Yes, but both are heavy and hold water. Tell us the volume, because heavy material is priced differently from light debris."),
  ("Do you take fencing and landscape timbers?","Yes, including posts. Mention concrete footings if there are any."),
  ("How fast can you come after a storm?","We will tell you honestly. After a major storm everyone calls at once and we will not promise a slot we cannot hold."),
  ("Do you take dirt and rock?","In limited quantities. Both are extremely heavy and hit the truck weight limit fast, so these are quoted by weight.")],
 "related":["shed-removal","construction-debris-removal","deck-and-fence-removal"],
},
{
 "slug":"tv-and-electronics-removal","name":"TV and Electronics Removal",
 "h1":"TV and Electronics Removal in Orlando",
 "blurb":"Televisions, computers and e-waste taken to a recycler instead of a landfill.",
 "intro":[
  "Electronics are one of the few categories where dumping genuinely matters. Old televisions and monitors contain leaded glass, and circuit boards contain heavy metals that should not go into the ground.",
  "Most curbside services will not take a television at all, which is why so many of them end up beside a dumpster. We take them to an e-waste processor."],
 "takes":["Flat screen and CRT televisions","Computers, laptops and monitors","Printers, scanners and copiers","Stereo and home theatre equipment","Game consoles","Phones and tablets in bulk","Cables, keyboards and peripherals","Office electronics in volume"],
 "faqs":[
  ("Do you take old tube televisions?","Yes. CRT televisions are heavy and contain leaded glass, which is exactly why they should not go in a dumpster and why many services refuse them."),
  ("Where do the electronics actually go?","To an e-waste recycler that separates the recoverable material and handles the rest properly. Not the landfill."),
  ("What about the data on my computer?","Remove or wipe the drive before we take it. We are a hauling company and do not perform certified data destruction. For business machines with sensitive data, use a certified ITAD provider instead."),
  ("Can you take a wall-mounted TV down?","Yes. Tell us it is mounted so we bring tools, and we can take the bracket too."),
  ("Do you take printers and copiers?","Yes. Office copiers are heavy and often need two people and a dolly, so mention the size."),
  ("Is there a fee for electronics?","E-waste usually carries a processing fee at the facility and that gets reflected in the price. Tell us the count when you book so the quote is right."),
  ("Can you take a working TV to donation instead?","If it works, say so. Working electronics can sometimes go to a donation partner, which is a better outcome than recycling."),
  ("Do you take batteries?","Small household batteries with a load, yes. Car and marine batteries, no, those need a dedicated drop-off, and most auto parts stores take them."),
  ("Can you clear a whole office of electronics?","Yes. Give us a count and we will bring the right truck and crew.")],
 "related":["office-cleanout","appliance-removal","garage-cleanout"],
},
]

SERVICES += [
{
 "slug":"single-item-pickup","name":"Single Item Pickup","h1":"Single Item Junk Pickup in Orlando",
 "blurb":"One couch, one fridge, one treadmill. You do not need a full truckload to call us.",
 "intro":[
  "Not every job is a garage. Most people calling us have exactly one thing they cannot move and nowhere to put it.",
  "Single items are priced as a small partial load, not as a full truck, and we take it from the room it is in rather than the curb."],
 "takes":["One sofa, recliner or mattress","One appliance","One TV or piece of exercise equipment","One desk, dresser or cabinet","A small pile of boxes","One hot tub cover or patio set","A few bags of debris","Anything two people can carry"],
 "faqs":[
  ("Is there a minimum charge?","Yes, there is a floor, because a truck and crew still have to drive out. But a single item costs a fraction of a full load and you will know the number before we touch it."),
  ("Do you really come out for one thing?","Yes, and it is a large share of what we do. Mattresses, recliners and refrigerators are the three most common single items."),
  ("Can you take it from inside?","Yes, including upstairs. That is the part you are paying for."),
  ("How fast can you get a single item?","Often same day in Lake Nona and nearby, because a one-item job slots into a schedule easily."),
  ("Is it cheaper if I put it at the curb?","No, and in most local HOAs and in Belle Isle you should not. The price is the same either way, so leave it where it is."),
  ("Can I add a few more things when you arrive?","Yes. We requote on the spot before loading, and it is almost always cheaper to add to an existing trip than to book a second one."),
  ("Do you take one item from an apartment?","Yes. Give us the floor and whether there is an elevator when you book."),
  ("What is the most common single item you take?","Mattresses, by a distance. They are the item almost no standard service will accept.")],
 "related":["furniture-removal","mattress-removal","appliance-removal"],
},
{
 "slug":"exercise-equipment-removal","name":"Exercise Equipment Removal",
 "h1":"Exercise Equipment Removal in Orlando",
 "blurb":"Treadmills, home gyms and weight sets taken out of the spare room without damaging the doorframe.",
 "intro":[
  "Home gym equipment is deceptively difficult. A treadmill is far heavier than it looks, most of it was assembled inside the room it is in, and a lot of it will not go back through the door in one piece.",
  "We dismantle what needs dismantling and carry it out."],
 "takes":["Treadmills and ellipticals","Exercise bikes and rowers","Home gym systems and racks","Free weights and plates","Weight benches","Punching bags","Yoga and gym flooring","Peloton and similar connected equipment"],
 "faqs":[
  ("Will you take a treadmill apart?","Yes where needed. Most treadmills were assembled in the room and will not fit back out whole. We fold, dismantle and carry."),
  ("Can you get it down stairs?","Yes. Treadmills coming down stairs is a two or three person job and we bring the crew rather than risk the wall or the backs."),
  ("Do you take free weights?","Yes. Weights are dense so they fill the truck by weight rather than space. Give us a rough total so we quote it correctly."),
  ("Is it worth donating instead?","If it works, possibly, and we will tell you. Working cardio equipment can sometimes go to a donation partner. Broken equipment cannot be donated and a charity will refuse it."),
  ("Do you remove the gym flooring too?","Yes. Rubber tiles and rolled flooring, including adhesive-backed if it comes up."),
  ("How much does it cost to remove a treadmill?","A single treadmill is a small partial load. You will have the price before it moves."),
  ("Can you take a full home gym system?","Yes. Cable machines and power racks are bolted assemblies, so tell us what you have and we will bring tools."),
  ("Will you damage the doorframe?","We pad frames and corners and dismantle rather than force. If something genuinely will not fit without damage, we stop and tell you first.")],
 "related":["single-item-pickup","furniture-removal","garage-cleanout"],
},
{
 "slug":"piano-and-pool-table-removal","name":"Piano and Pool Table Removal",
 "h1":"Piano and Pool Table Removal in Orlando",
 "blurb":"The two heaviest things in most houses, moved by people who have done it before.",
 "intro":[
  "Pianos and pool tables are the jobs where doing it wrong causes real injury and real property damage. An upright piano runs several hundred pounds with all of it high and unbalanced. A slate pool table is heavier still, in pieces that each need two people.",
  "Neither is a job for a couple of friends and a pickup truck."],
 "takes":["Upright and spinet pianos","Baby grand and grand pianos","Organs and electric pianos","Slate and non-slate pool tables","Air hockey and foosball tables","Arcade cabinets","Large safes (ask first)","Other oversized heavy items"],
 "faqs":[
  ("Can you take an upright piano?","Yes, routinely. Tell us whether there are stairs and how many, because that changes the crew size significantly."),
  ("What about a grand piano?","Yes, but it needs a look first. Grands come apart for moving and the route out matters. Send photos and tell us the floor."),
  ("Do you disassemble a pool table?","Yes. Slate tables come apart into the frame, rails and slate sections, and the slate is the heavy part. It is the only safe way to move one."),
  ("Is the piano worth anything?","Usually less than people hope. Most used uprights have little or no resale value and many dealers will not take them. If yours is a recognised maker in good condition, get it appraised before disposal."),
  ("Can it be donated?","Sometimes, if it is in playable condition and holds tune. Schools and churches occasionally take them. A piano that has not been tuned in twenty years and sat in Florida humidity generally cannot be donated."),
  ("How much does piano removal cost?","More than a regular item because of the crew and equipment needed. Stairs and access drive the number more than the piano itself."),
  ("Can you get it out of a second floor?","Usually yes. Tell us before you book, because it changes how many people we send."),
  ("Do you take safes?","Ask first. Small safes yes. Large gun safes and floor safes are extremely heavy and may need specialist equipment.")],
 "related":["furniture-removal","single-item-pickup","house-cleanout"],
},
{
 "slug":"carpet-removal","name":"Carpet Removal","h1":"Carpet Removal and Disposal in Orlando",
 "blurb":"Old carpet, pad and tack strip pulled up and hauled, so the new floor can go in.",
 "intro":[
  "Carpet removal is easy to start and unpleasant to finish. Pulling it up takes an hour. Cutting it into manageable rolls, getting the pad and staples out, and finding somewhere that will take it is the rest of the day.",
  "Old carpet in Florida is also often holding more moisture and dust than anyone expects, which is its own reason to get it out of the house rather than into a garage."],
 "takes":["Carpet and underlay","Tack strip and staples","Vinyl and laminate flooring","Area rugs","Glued-down commercial carpet tile","Transition strips and trim","Subfloor material (ask first)","Furniture moved to access the floor"],
 "faqs":[
  ("Do you pull the carpet up or only haul it?","Both. We pull it, cut it, remove the pad and the tack strip, and haul all of it."),
  ("Do you take the staples out?","We get the tack strip and the bulk of the staples. A flooring installer will do a final pass before laying new flooring, and we will not pretend otherwise."),
  ("Can you move the furniture?","Yes, and tell us so we bring the crew. It is easier and cheaper to do it in one visit than to have you move it and us come after."),
  ("How is carpet priced?","By volume once it is rolled, which is why square footage is the number we need. Give us room dimensions or total square footage."),
  ("Do you take vinyl and laminate too?","Yes, and glued-down vinyl is slower to lift than carpet, so mention which you have."),
  ("What about asbestos in old flooring?","Serious question in an older house. Vinyl tile and the black adhesive under it from before about 1980 can contain asbestos. It needs testing first and a licensed abatement contractor if positive. We do not disturb it."),
  ("Is old carpet recyclable?","Some carpet is, depending on fibre type and condition, though options are limited locally. Wet or mould-affected carpet is not and has to be landfilled."),
  ("Can you do a whole house?","Yes. Whole-house carpet is a large volume job, so give us total square footage for an accurate number.")],
 "related":["construction-debris-removal","house-cleanout","office-cleanout"],
},
{
 "slug":"deck-and-fence-removal","name":"Deck and Fence Removal",
 "h1":"Deck and Fence Removal in Orlando",
 "blurb":"Rotted decking and downed fencing taken apart and hauled, posts and footings included.",
 "intro":[
  "Florida weather takes decks and fences apart on its own schedule. Wood rots, posts fail at ground level, and a storm finishes what humidity started.",
  "We demolish and haul in the same visit, including the posts, which is the slow part everyone underestimates."],
 "takes":["Wood and composite decking","Deck framing and railings","Wood, vinyl and chain link fencing","Fence posts including concrete footings","Gates and hardware","Pergolas and arbors","Lattice and screening","Storm-damaged sections"],
 "faqs":[
  ("Do you remove the fence posts too?","Yes, including posts set in concrete. Footings are the slow part of a fence job, so tell us how many sections and whether the posts are concreted when you ask for a quote."),
  ("Can you take just a damaged section?","Yes. Storm repairs often only need a run of a few panels, and that is a small job."),
  ("Do you remove the whole deck including framing?","Yes, decking, joists, beams and posts. If the deck is attached to the house, we detach it and leave the ledger area clear for whoever is repairing the wall."),
  ("Is a permit needed?","For most residential deck and fence demolition, usually not, but requirements vary between Orange County, Osceola County and cities like Belle Isle and St. Cloud. Check with your building department. We will not guess on your behalf."),
  ("What about the concrete footings?","We pull them where we can. Very large or deep footings may need to be broken up, and concrete is priced by weight, so we will quote that separately."),
  ("Do you take composite decking?","Yes. It does not rot the way wood does but it still has to go somewhere, and it is not recyclable through normal channels."),
  ("Can you get to a back yard fence?","Usually. Tell us the narrowest access point and we will size the pieces to fit through it."),
  ("How long does it take?","A typical residential fence run is a half day. A full deck with footings can be a full day or more.")],
 "related":["shed-removal","yard-waste-removal","construction-debris-removal"],
},
{
 "slug":"playset-and-swing-set-removal","name":"Playset and Swing Set Removal",
 "h1":"Playset and Swing Set Removal in Orlando",
 "blurb":"Outgrown wooden playsets and trampolines dismantled and hauled, including the ground cover.",
 "intro":[
  "A wooden playset outlives its usefulness long before it falls down, and by the time the kids have outgrown it the wood has usually had years of Florida sun and rain.",
  "They are bolted assemblies, often into concrete, and taking one apart safely takes tools and time most people would rather not spend."],
 "takes":["Wooden swing sets and playsets","Metal swing sets","Trampolines with enclosures","Playhouses and forts","Basketball hoops, in-ground and portable","Rubber mulch and play surfacing","Sandboxes","Concrete footings (ask first)"],
 "faqs":[
  ("Do you take the playset apart?","Yes. They are bolted assemblies and we dismantle them into pieces that fit through the gate and into the truck."),
  ("What about the concrete the posts are set in?","We pull footings where we can. Mention them when you ask for a quote because they add time and weight."),
  ("Can you take the rubber mulch underneath?","Yes. It is heavy and holds water, so tell us roughly how much area it covers."),
  ("Do you take trampolines?","Yes, frame, mat, springs and enclosure. Anchored trampolines take a bit longer."),
  ("Can you remove an in-ground basketball hoop?","Yes. The pole is usually set in a substantial concrete footing, so that gets quoted as part of the job rather than assumed."),
  ("Is an old playset worth selling?","Rarely worth the effort once it has had a few Florida summers. Sun-damaged wood, faded plastic and rusted hardware sell for very little, and dismantling and delivering it for a buyer is most of the work."),
  ("How long does it take?","Most residential playsets are a half day including footings and haul."),
  ("Can you get it out through a side gate?","That is why we dismantle. Give us the narrowest gate width and we size the pieces accordingly.")],
 "related":["shed-removal","deck-and-fence-removal","yard-waste-removal"],
},
{
 "slug":"scrap-metal-removal","name":"Scrap Metal Removal","h1":"Scrap Metal Removal in Orlando",
 "blurb":"Appliances, fencing, racking and general metal taken to a recycler rather than a landfill.",
 "intro":[
  "Metal is the material we most want to see in a load. It recycles cleanly, it has genuine scrap value, and sending it to a landfill is both worse environmentally and worse economically.",
  "If a large share of your pile is metal, say so, because it can work in your favour."],
 "takes":["Appliances and white goods","Metal fencing and gates","Bed frames and bases","Filing cabinets and lockers","Warehouse racking and shelving","Mowers and garden equipment","Pipe, ducting and conduit","General mixed scrap"],
 "faqs":[
  ("Do you pay for scrap metal?","Generally no, and be cautious of anyone who promises to. The scrap value of a typical household load is far less than the cost of a truck and crew. What metal does is keep your price down and keep material out of a landfill."),
  ("Do you take appliances as scrap?","Yes. Most appliances are largely steel. Refrigerant units go through a certified recycler first so the refrigerant is recovered."),
  ("Will you take just metal, nothing else?","Yes. A metal-only load is straightforward and it is the cleanest kind of job we do."),
  ("Do you take car parts?","Most metal parts yes. What we cannot take is anything holding fluid: fuel tanks with fuel in them, oil-filled components, or batteries."),
  ("What about propane tanks and pressure vessels?","No. Anything pressurised is a hard no regardless of it being metal. Grill tanks can usually be exchanged at a retailer."),
  ("Can you clear warehouse racking?","Yes, including disassembly. Tell us the run length and height."),
  ("Do you take old tools and machinery?","Yes, if we can move it. Large fixed machinery may need equipment we do not carry, and we will tell you before you book."),
  ("Is metal cheaper to haul than general junk?","It can work out that way on a metal-heavy load, because the disposal side costs us less. Mention it when you ask for the quote.")],
 "related":["appliance-removal","garage-cleanout","construction-debris-removal"],
},
]
