# Service-area content. Each entry is written to be genuinely different from the
# others: different housing stock, different jobs, different questions. Thin
# near-duplicate location pages are what Google's helpful-content system demotes,
# so do not template these down to a name swap.

AREAS = [
{
 "slug":"lake-nona","name":"Lake Nona","drive":"Home base","zips":"32827, 32832",
 "blurb":"Junk removal in Lake Nona, from new-build move-in debris to apartment turnovers around Medical City.",
 "intro":[
  "We are based on Narcoossee Road, which puts our truck inside Lake Nona rather than driving in from across town. For most of 32827 and 32832 that means we can usually be at the curb the same day you call.",
  "Lake Nona is the newest housing stock in Orlando, and that shapes the work. Most of what we haul here is not decades of accumulation. It is move-in debris: flattened wardrobe boxes stacked to the garage ceiling, packing foam, the old sectional that did not survive the move, and whatever the builder left in the garage.",
  "The other half is the rental side. The apartments and townhomes around Medical City turn over constantly, and a unit has to be empty before the next lease starts. We work to that deadline."],
 "hoods":["Laureate Park","Village Walk","Eagle Creek","Northlake Park","Storey Park","Isles of Lake Nona","Medical City"],
 "angle_h":"What Lake Nona actually calls us for",
 "angle":[
  ("New-build move-in debris","Boxes, foam, pallet wood, plastic wrap and the packaging from every appliance and piece of furniture that arrived at once. It fills a garage faster than people expect."),
  ("Apartment and townhome turnovers","Whatever the last tenant left, cleared and swept, on a date that works with the next lease."),
  ("Furniture that did not fit","The sectional that will not go up the stairwell, the dining set that is wrong for the new room, the mattress being replaced."),
  ("Office and clinic cleanouts","Medical City suites change hands. We take out the desks, chairs, casework and files.")],
 "faqs":[
  ("Do you do same-day junk removal in Lake Nona?","Usually, yes. We are based on Narcoossee Road, so there is no cross-town drive to get to 32827 or 32832. Call before noon and same afternoon is normally doable. Later in the day we will tell you honestly whether it is today or first thing tomorrow."),
  ("My HOA does not allow anything at the curb. Is that a problem?","No, and it is the most common question we get here. Most Lake Nona communities have rules about what can sit outside and for how long. We do not stage anything at the curb. We carry it from where it is straight into the truck and leave with it the same visit."),
  ("Can you get into Laureate Park and Village Walk with a truck?","Yes. The alleys and rear-loaded garages are tighter than a standard street, so we park where we can legally fit and carry from there. Tell us if you are on an alley-load lot and we will plan for it."),
  ("I have a garage full of flattened moving boxes. Do you take cardboard?","Yes, and cardboard is one of the better outcomes. It is clean recyclable material, so it goes to recycling rather than landfill. Volume is what sets the price, and flattened boxes compress well, which usually works in your favor."),
  ("Do you handle apartment turnovers near Medical City?","Yes. Give us the unit, the access details and the date the unit has to be clear. We work turnover deadlines regularly and we will send photos when the unit is empty."),
  ("Can you take the builder debris left in my new home?","Leftover trim, packaging, drywall offcuts and the like, yes. What we cannot take is anything hazardous: paint, solvents, fuel, propane or chemicals. Those need household hazardous waste drop-off."),
  ("Will you take the appliance packaging and the old appliance?","Both. The packaging is bulky but light. The appliance itself we take too, and if it still runs we try to route it to a donation partner rather than scrap it."),
  ("Do I need to be home?","No. Plenty of Lake Nona jobs are handled with a garage code or a photo of what goes. We confirm by text before we load and send photos when we are done."),
  ("Is there a trip fee for Lake Nona?","No. Lake Nona is our home base, so there is no trip charge anywhere in 32827 or 32832."),
  ("Can you do a second-floor or third-floor unit?","Yes. Stairs are part of the job and we do not charge extra for them. Tell us the floor when you call so we bring the right number of people.")],
 "nearby":["narcoossee","conway","belle-isle","st-cloud","kissimmee"],
},
{
 "slug":"narcoossee","name":"Narcoossee","drive":"About 10 minutes","zips":"32832, 34771",
 "blurb":"Junk removal in Narcoossee, including acreage properties, sheds, fencing and outbuildings.",
 "intro":[
  "Narcoossee is a short run down the road from us, and the work here looks different from the subdivisions north of it. Lots are bigger, a lot of properties have outbuildings, and the junk is often outside rather than in a garage.",
  "That means sheds that have collapsed or rotted, fence sections replaced after a storm, old above-ground pools, trailers, tractor parts and the general accumulation that happens when a property has room to accumulate.",
  "Long driveways and gates are normal here. Tell us about them when you call and we will bring the right truck and plan the approach instead of discovering it on arrival."],
 "hoods":["Live Oak Estates","Eagle Creek","Tyson Ranch","Isle of Pines","Narcoossee Road corridor","Split Oak area"],
 "angle_h":"What we haul in Narcoossee",
 "angle":[
  ("Sheds and outbuildings","Rotted, storm-damaged or simply unwanted. We can take them down and haul the material away in the same visit."),
  ("Fencing","Wood, vinyl and chain link, including posts. Storm replacement work generates a lot of this."),
  ("Above-ground pools and hot tubs","Drained, cut down and removed. The deck around it too if that is going."),
  ("Property and barn cleanouts","Years of stored equipment, feed bags, pallets, scrap metal and whatever has accumulated in a building nobody has opened in a while.")],
 "faqs":[
  ("Can you get down a long dirt or gravel driveway?","Usually yes. What stops us is soft ground after heavy rain and low tree limbs. Send a photo of the driveway when you call and we will tell you straight whether the truck makes it or whether we need to shuttle from a firmer spot."),
  ("Do you tear down sheds, or only haul them if they are already down?","We take them down. Wood and metal sheds are routine. If the shed has a concrete pad, tell us up front, because whether the pad goes changes the job significantly."),
  ("Is there a trip fee out to Narcoossee?","No. We are about ten minutes away on Narcoossee Road, so the same pricing applies as anywhere else we serve."),
  ("Can you remove old fencing including the posts?","Yes, including posts set in concrete. Post footings are slow work, so tell us roughly how many sections and whether the posts are concreted when you ask for a quote."),
  ("What about an above-ground pool?","Yes. It needs to be drained before we arrive, and we will cut it down and haul it. If there is a deck or surround going too, mention it, because that is often the larger half of the job."),
  ("Do you take scrap metal and old equipment?","Yes. Metal is one of the things we genuinely want, because it recycles cleanly. Old mowers, appliances, fencing, bed frames and general scrap are all fine."),
  ("I have a gate with a code. How does that work?","Give us the code or the gate contact when you book. Plenty of our Narcoossee jobs happen without the owner on site."),
  ("Can you handle a full barn or outbuilding cleanout?","Yes, and these are usually a multi-truck job. We would rather look at photos or walk it first and give you a real number than guess and surprise you."),
  ("What will you not take?","Paint, solvents, fuel, pesticides, propane tanks, asbestos and anything else classed as hazardous. On rural properties old fuel cans and pesticide containers come up often, so it is worth checking before we arrive."),
  ("Do you take yard debris and tree limbs?","Yes, cut to manageable lengths. Whole felled trees and stumps are a different trade and we will tell you if you need a tree service instead of us.")],
 "nearby":["lake-nona","st-cloud","kissimmee","conway","belle-isle"],
},
{
 "slug":"conway","name":"Conway","drive":"About 15 minutes","zips":"32806, 32812",
 "blurb":"Junk removal in Conway and the Lake Conway chain, including older homes, garages and estate cleanouts.",
 "intro":[
  "Conway is an older part of Orlando, and the housing reflects it. A lot of these homes went up between the 1950s and the 1970s, which means real garages, real attics, and families who have been in the same house long enough to fill both.",
  "The jobs here skew toward decades of accumulation rather than move-in debris: a garage nobody has parked in since the nineties, an attic full of boxes, a Florida room used as storage.",
  "Being on the Lake Conway chain also brings boat and dock material, and older streets with narrower driveways and mature trees, which we plan around."],
 "hoods":["Dover Shores","Pershing","Conway Estates","Lake Conway Estates","Gatlin","Anderson Park"],
 "angle_h":"What Conway calls us for",
 "angle":[
  ("Garage and attic cleanouts","Thirty years in one house fills a lot of space. We carry it down and out, you do not lift anything."),
  ("Estate cleanouts","When a long-held family home changes hands. We work slowly enough that nothing meaningful gets thrown out by mistake."),
  ("Boat, dock and lake gear","Old docks, boat covers, trailers, canoes, lifts and the rest of what collects on a lakefront property."),
  ("Furniture and appliances","Heavy old pieces out of houses with narrow hallways and tight stairs. This is exactly what we are for.")],
 "faqs":[
  ("Can you get a truck down a 1960s driveway?","Usually. Conway driveways are narrower than modern ones and the trees are mature, so if we cannot get the truck all the way in we park at the street and carry. That does not change your price."),
  ("Do you do attic cleanouts?","Yes, as long as there is safe floored access and a usable pull-down or stair. Our crew goes up and brings it down. If the attic is unfloored we will tell you before we start rather than put someone through a ceiling."),
  ("How do estate cleanouts work?","We go at your pace. Anything you want set aside gets set aside, and we point out anything that looks like it might matter rather than assuming. Usable furniture goes to donation where we can, and we can get you a donation receipt."),
  ("Can you remove an old dock or boat lift?","Dock material and lift components that are already out of the water, yes. Anything requiring in-water work or a marine contractor is outside what we do, and we will say so rather than take the job."),
  ("My house is from the sixties. Do you worry about asbestos?","We do, and you should too. Popcorn ceilings, old floor tile and certain pipe wrap from that era can contain asbestos. We do not disturb or haul suspected asbestos material. It needs testing and a licensed abatement contractor first."),
  ("Do you take old appliances from a garage?","Yes. Fridges, freezers, washers, dryers, water heaters and window units. Refrigerant appliances get handled through a recycler rather than dumped."),
  ("Can you take a piano?","Usually, and this comes up more in Conway than anywhere else we serve. Uprights are routine. Grands and anything going down stairs need a look first, so send a photo."),
  ("Is there a trip fee to Conway?","No. Conway is about fifteen minutes from our base and there is no trip charge."),
  ("What if I only have a couple of items?","That is fine and it is a common Conway call. Single-item and partial-load pricing exists precisely so you are not paying for a full truck to move one recliner."),
  ("Will you sweep up after?","Yes. We broom-sweep the space we cleared. A garage that has been full for twenty years will need more than a broom to look new, but you will not be cleaning up after us.")],
 "nearby":["belle-isle","lake-nona","narcoossee","kissimmee","st-cloud"],
},
{
 "slug":"belle-isle","name":"Belle Isle","drive":"About 18 minutes","zips":"32809, 32812",
 "blurb":"Junk removal in Belle Isle, serving the Lake Conway chain, Nela Isle and Venetian Gardens.",
 "intro":[
  "Belle Isle is its own incorporated city rather than part of unincorporated Orange County, which matters more than people expect. It has its own rules about what can sit at the curb and for how long, and enforcement is real because it is a small city where things get noticed.",
  "Our approach here is simple: nothing goes to the curb. We load from where the item sits and leave with it in the same visit, so there is no window where a pile is sitting outside your house.",
  "The lake frontage on the Conway chain also means the usual waterfront accumulation, and the streets around Nela Isle and Venetian Gardens are tight enough that we plan the park before we arrive."],
 "hoods":["Nela Isle","Venetian Gardens","Lake Conway shoreline","Hoffner Avenue corridor","Cornerstone area"],
 "angle_h":"What Belle Isle calls us for",
 "angle":[
  ("Same-visit removal with nothing left at the curb","The main reason people here call a hauler instead of waiting on a bulk pickup."),
  ("Lakefront and dock material","Old docks, covers, lifts, canoes, patio furniture and the rest of what a waterfront lot collects."),
  ("Garage and home cleanouts","Older homes, long ownership, full garages. Same story as neighboring Conway."),
  ("Furniture and appliance removal","Heavy items out of houses with narrow access, carried rather than dragged.")],
 "faqs":[
  ("Belle Isle has rules about curbside junk. How do you handle that?","By not using the curb at all. We carry everything from where it is directly into the truck and drive away with it. Nothing sits outside your house waiting for a pickup day, so there is nothing for the city to take issue with."),
  ("Should I check with the city before I book?","For a normal household removal, no, because nothing goes on public property. If a project involves demolition, a dumpster on the street or structural work, check with Belle Isle first, since those can carry permit requirements we cannot speak to on your behalf."),
  ("Can your truck handle the narrow streets around Nela Isle?","Yes, with a little planning. Some of those streets and driveways are tight, so we may park on the street and carry. Send a photo of the access if you are unsure and we will confirm before the day."),
  ("Do you take dock and waterfront material?","Yes, once it is out of the water. Decking, railings, covers, old lifts and shoreline junk. In-water removal needs a marine contractor, not us."),
  ("Is there a trip fee for Belle Isle?","No. It is roughly eighteen minutes from our base and pricing is the same as everywhere else we serve."),
  ("Can you do a whole-house cleanout?","Yes. Whole-house jobs usually take multiple truckloads, and we would rather walk it or see photos first and give you a real number than quote blind."),
  ("Do you take mattresses?","Yes. Mattresses are one of the worst things to leave at a curb and one of the more annoying things to dispose of yourself, which is why they are one of our most common single items."),
  ("What about paint and pool chemicals?","Neither, unfortunately. Paint, pool chemicals, solvents and fuel all need household hazardous waste drop-off. We will tell you what in your pile we cannot take before we start loading, not after."),
  ("Can you come on a Saturday?","Yes. We run Monday through Saturday, 7am to 7pm."),
  ("Do you give a price before you start?","Yes. You get the number before anything goes in the truck, and if the load ends up smaller than we estimated, the price comes down.")],
 "nearby":["conway","lake-nona","narcoossee","kissimmee","st-cloud"],
},
{
 "slug":"st-cloud","name":"St. Cloud","drive":"About 20 minutes","zips":"34769, 34771, 34772",
 "blurb":"Junk removal in St. Cloud, from historic downtown homes to new subdivisions and acreage off Canoe Creek.",
 "intro":[
  "St. Cloud has two distinct halves and we work both. There is the older core around New York Avenue and East Lake Tohopekaliga, where the houses are small, old and long-owned. Then there is everything that has gone up in the last decade toward Narcoossee and Canoe Creek, which is all new construction.",
  "The old half generates cleanouts: garages, sheds, attics, and estates as houses change hands. The new half generates move-in debris and the occasional builder leftover.",
  "Outside both, there is still real acreage in St. Cloud, which brings outbuildings, equipment and the kind of accumulation that only happens when a property has space."],
 "hoods":["Historic downtown / New York Ave","East Lake Toho","Canoe Creek","Hickory Tree","Narcoossee border","Nova Road area"],
 "angle_h":"What St. Cloud calls us for",
 "angle":[
  ("Garage, shed and property cleanouts","The older core generates decades of stored material. We clear it in one visit where we can."),
  ("Estate cleanouts","Long-held homes changing hands, worked carefully rather than fast."),
  ("New-build move-in debris","Boxes, packaging and builder leftovers from the newer subdivisions."),
  ("Acreage and outbuildings","Barns, workshops, equipment, scrap metal and whatever has accumulated out of sight.")],
 "faqs":[
  ("Do you charge extra to come out to St. Cloud?","No. St. Cloud is about twenty minutes from our base on Narcoossee Road and we do not add a trip fee."),
  ("Can you do same-day in St. Cloud?","Often, though less reliably than in Lake Nona simply because of the drive. Call early and we will tell you honestly whether it is today or tomorrow morning rather than promise and miss."),
  ("Do you take material from a historic downtown home?","Yes, with a caveat. Homes from that era can contain asbestos in floor tile, pipe wrap and ceiling texture, and lead paint on old trim. We do not disturb or haul suspected asbestos material. It needs testing and a licensed abatement contractor."),
  ("Can you clear a barn or workshop?","Yes. These are usually multiple loads. Send photos or let us walk it and you will get a real number instead of an optimistic one."),
  ("Do you take tractors, mowers and old equipment?","Yes, if we can move it. Anything seized, buried or too heavy for our crew and a winch needs equipment we do not carry, and we will tell you that before you book."),
  ("What about tires?","Usually yes, but tell us the count when you call. Tires carry a disposal fee almost everywhere and a large pile changes the price, so we would rather that be part of the quote than a surprise."),
  ("Can you handle a rental turnover?","Yes. Tell us the date the unit has to be clear and we will work to it. We send photos when the unit is empty."),
  ("Do you take fencing and yard debris?","Yes. Fence panels and posts, cut limbs and general yard waste. Whole trees and stumps need a tree service."),
  ("I am on acreage with a long driveway. Is that a problem?","Usually not, but soft ground after rain and low limbs are the two things that stop us. A photo of the driveway when you call saves everyone a wasted trip."),
  ("Do you donate anything?","Where we can. Usable furniture and working appliances go to local donation partners rather than the landfill, and we can get you a receipt if you want one.")],
 "nearby":["narcoossee","kissimmee","lake-nona","conway","belle-isle"],
},
{
 "slug":"kissimmee","name":"Kissimmee","drive":"About 25 minutes","zips":"34741, 34744, 34746, 34747",
 "blurb":"Junk removal in Kissimmee, including vacation rental turnovers and property manager accounts along the 192 corridor.",
 "intro":[
  "Kissimmee runs on short-term rentals, and that creates a kind of junk removal work that barely exists elsewhere in our area. Vacation homes replace furniture on a cycle, guests break things, and a unit has to be guest-ready between bookings with no gap.",
  "That means we schedule around check-out and check-in rather than around a normal workday, and we are used to property managers handling several properties at once.",
  "Outside the rental corridor, Kissimmee has plenty of ordinary residential work too: garages, estates, furniture and appliances in the older neighborhoods around Lake Tohopekaliga and downtown."],
 "hoods":["192 corridor","Old Town area","Celebration side","Buenaventura Lakes","Poinciana","Lake Tohopekaliga / downtown"],
 "angle_h":"What Kissimmee calls us for",
 "angle":[
  ("Vacation rental turnovers","Furniture swaps and clear-outs scheduled into the gap between guests, not whenever we happen to be free."),
  ("Property manager accounts","Several properties, one point of contact, photo confirmation on every job."),
  ("Bulk furniture replacement","When a rental gets refurnished, the old set has to leave the same day the new one lands."),
  ("Residential cleanouts","Garages, estates, appliances and furniture in the neighborhoods off the tourist corridor.")],
 "faqs":[
  ("Can you work around guest check-in and check-out?","Yes, and this is most of what we do in Kissimmee. Give us the window and we will work inside it. If the window is tight, tell us up front so we bring enough crew to finish inside it."),
  ("Do you work with property managers on multiple units?","Yes. One contact, several addresses, and photo confirmation for each unit so you can prove the job was done without driving out to look."),
  ("Can you do a furniture swap the same day the new furniture arrives?","Yes, and timing matters. Tell us when the delivery lands so we clear the old set before it, not after. Otherwise you have two sets of furniture in one house and nowhere to put either."),
  ("Is there a trip fee for Kissimmee?","No. Kissimmee is about twenty-five minutes out and pricing is the same as everywhere else we serve."),
  ("Do you take pool and patio furniture?","Yes. Sun-wrecked patio sets are one of the most common vacation rental items we haul."),
  ("Can you handle mattresses in bulk?","Yes. Rentals replace mattresses on a schedule and we are set up for volume. Tell us the count and sizes when you book."),
  ("What if the unit has a gate code or lockbox?","That is normal here. Give us the access details and we will handle it without anyone meeting us on site. Photos when we are done."),
  ("Do you take TVs and electronics?","Yes. Electronics go to an e-waste recycler rather than the landfill. Older tube TVs are heavy and awkward but we still take them."),
  ("Can you come on short notice if a guest leaves a mess?","We will try. Same-day out to Kissimmee is not guaranteed because of the drive, but tell us what happened and we will tell you the earliest we can realistically be there."),
  ("Do you take construction debris from a renovation?","Yes, within reason. Drywall, trim, flooring, cabinets and fixtures. What we do not take is hazardous material, and if the property is old enough to have asbestos flooring it needs testing first.")],
 "nearby":["st-cloud","narcoossee","lake-nona","belle-isle","conway"],
},
]

AREAS += [
{
 "slug":"hunters-creek","name":"Hunters Creek","drive":"About 20 minutes","zips":"32837",
 "blurb":"Junk removal in Hunters Creek, built around HOA rules and two-car garages that filled up.",
 "intro":[
  "Hunters Creek is a master-planned community from the nineties and early two-thousands, which means the houses are now old enough that the original owners have filled the garages and the kids have grown up and left equipment behind.",
  "It also means an active HOA. Nothing we do involves leaving anything at a curb, which is the main reason people here call a hauler rather than waiting on a bulk pickup."],
 "hoods":["Hunters Creek village communities","Town Center area","Osprey Ridge","Eagle Creek Village","Golfview"],
 "angle_h":"What Hunters Creek calls us for",
 "angle":[
  ("Garage cleanouts","Twenty-plus years in one house fills a two-car garage completely. This is the most common call here."),
  ("Outgrown kids' equipment","Playsets, trampolines, basketball hoops, exercise equipment and bedroom furniture after the kids move out."),
  ("Furniture and appliance replacement","Original appliances and furniture reaching end of life at roughly the same time across the community."),
  ("Downsizing and estate clearing","Original owners moving on, and the whole-house clearing that comes with it.")],
 "faqs":[
  ("My HOA does not allow items at the curb. How does that work?","It does not affect us, because we never use the curb. We carry everything from where it sits directly into the truck and leave with it the same visit. Nothing sits outside."),
  ("Do you need HOA approval to come out?","For a normal removal, no. Some communities require contractor registration for work involving equipment or demolition, so if your job involves a shed or a deck, check with your HOA first."),
  ("Can you take a wooden playset from the back yard?","Yes. We dismantle it, including the posts and footings, and carry it out through the gate. Give us the narrowest gate width."),
  ("Is there a trip fee for Hunters Creek?","No. It is about twenty minutes and there is no trip charge."),
  ("Do you take trampolines and basketball hoops?","Yes to both. In-ground basketball poles have a substantial concrete footing, so mention that when you ask for a quote."),
  ("Can you do a garage cleanout in one visit?","Usually. A packed two-car garage is most of a day and often more than one truckload, but we will tell you honestly when we see the photos."),
  ("Do I have to sort it first?","No. Point out what stays and we work around it. Sorting is why garages stay full."),
  ("Do you take exercise equipment?","Yes. Treadmills and home gyms are heavy and were assembled in the room, so we dismantle and carry."),
  ("What about paint and garage chemicals?","Not those. Liquid paint, fuel, propane, pesticides and pool chemicals all need household hazardous waste drop-off. We will point them out before we start loading.")],
 "nearby":["meadow-woods","lake-nona","kissimmee","belle-isle","celebration"],
},
{
 "slug":"meadow-woods","name":"Meadow Woods","drive":"About 12 minutes","zips":"32824",
 "blurb":"Junk removal in Meadow Woods, close enough for same-day on most jobs.",
 "intro":[
  "Meadow Woods sits between us and the airport, which makes it one of the quickest runs we do. Same-day is realistic here more often than almost anywhere else we serve.",
  "The housing is a mix: established homes from the eighties and nineties alongside newer construction, plus a significant rental population. That produces both long-accumulation garage cleanouts and regular turnover work."],
 "hoods":["Meadow Woods","Wyndham Lakes","Southchase","Villages at Southport","Landstar area"],
 "angle_h":"What Meadow Woods calls us for",
 "angle":[
  ("Same-day single items","We are close enough that a one-item pickup fits into most days' schedules."),
  ("Rental turnovers","A substantial rental population means regular move-out clearing on lease deadlines."),
  ("Garage and shed cleanouts","Established homes with decades of accumulation."),
  ("Furniture and appliance removal","The everyday work, and the quickest to schedule here.")],
 "faqs":[
  ("How quickly can you get to Meadow Woods?","Faster than almost anywhere we serve. It is roughly twelve minutes from our base, so same-day is realistic on most days if you call in the morning."),
  ("Is there a trip fee?","No."),
  ("Do you handle rental move-outs?","Yes. Give us the date the unit has to be clear and we work to it, with photos when it is empty."),
  ("Can you take a single mattress?","Yes, and it is one of our most common calls. Priced as a small partial load, taken from the bedroom not the curb."),
  ("Do you clear sheds?","Yes, including taking the shed down if it is going. Tell us if there is a concrete pad."),
  ("Can you come on a Saturday?","Yes. Monday through Saturday, 7am to 7pm."),
  ("Do I need to be home?","Not necessarily. A gate code, a garage code or a photo of what goes is often enough. We confirm by text before loading."),
  ("What does a garage cleanout cost?","By volume. Send photos of the garage and you will get a number that holds rather than a guess that climbs."),
  ("Do you take appliances?","Yes, including refrigerators and freezers, which go through a certified recycler so the refrigerant is recovered properly.")],
 "nearby":["lake-nona","hunters-creek","pine-castle","kissimmee"],
},
{
 "slug":"azalea-park","name":"Azalea Park","drive":"About 18 minutes","zips":"32807, 32822",
 "blurb":"Junk removal in Azalea Park, working mid-century homes with real garages and long ownership.",
 "intro":[
  "Azalea Park is one of the older established parts of east Orlando. Most of the housing dates from the fifties through the seventies, on generous lots, with detached garages and sheds that have been in use the whole time.",
  "That produces the deepest cleanouts we do. Not a year of clutter, but forty years of it, often across a garage, a shed and an attic at the same property."],
 "hoods":["Azalea Park","Engelwood Park","Ventura","Chickasaw","Monterey"],
 "angle_h":"What Azalea Park calls us for",
 "angle":[
  ("Deep garage and shed cleanouts","Decades of accumulation across multiple structures on one lot."),
  ("Estate cleanouts","Long-held homes changing hands as an older generation moves on."),
  ("Scrap metal and old equipment","Tools, mowers, appliances and general metal, which recycles well."),
  ("Furniture and appliances","Heavy old pieces out of houses with narrow hallways and tight doorways.")],
 "faqs":[
  ("Can you handle a garage that has been full for forty years?","Yes, and it is what we do most here. Expect more than one truckload and let us see photos so the quote is real."),
  ("My house is from the 1960s. Is asbestos a concern?","It can be. Floor tile and the black adhesive under it, pipe wrap and some ceiling textures from that era may contain asbestos. We do not disturb or haul suspected asbestos material. It needs testing and a licensed abatement contractor first."),
  ("Do you take old tools and machinery?","Yes, if we can move it. Mowers, hand tools, workbenches and general metal. Large fixed machinery may need equipment we do not carry."),
  ("Can you get a truck down an older driveway?","Usually. If not, we park at the street and carry, and that does not change your price."),
  ("Do you clear detached garages and sheds?","Yes, both, and we can take the shed itself down if it is going."),
  ("Is there a trip fee?","No. Azalea Park is about eighteen minutes out."),
  ("What happens to the metal?","It goes to a recycler. Metal is one of the better outcomes in this business and a metal-heavy load can work in your favour on price."),
  ("Do you take tires?","Usually, but give us a count. Tires carry a per-tire disposal fee almost everywhere, and old garages often have more than the owner remembers."),
  ("Can you work with a realtor on a pre-sale clearout?","Yes. Tell us the listing date and we will work to it.")],
 "nearby":["conway","pine-castle","belle-isle","waterford-lakes"],
},
{
 "slug":"pine-castle","name":"Pine Castle","drive":"About 18 minutes","zips":"32809, 32806",
 "blurb":"Junk removal in Pine Castle, covering older residential streets and the small commercial units along Orange Avenue.",
 "intro":[
  "Pine Castle mixes older residential streets with small commercial and light industrial along the Orange Avenue corridor, and we work both.",
  "On the residential side it is garages, estates and furniture out of older homes. On the commercial side it is small unit turnovers, workshop clearing and the kind of accumulated material that builds up in a business that has been in the same unit for years."],
 "hoods":["Pine Castle","Edgewood","Sky Lake","Orange Avenue corridor","Holden Heights"],
 "angle_h":"What Pine Castle calls us for",
 "angle":[
  ("Residential garage and estate cleanouts","Older housing stock with long ownership."),
  ("Small commercial unit clearing","Workshops, storage units and small business premises being handed back."),
  ("Scrap metal and equipment","Common on the commercial side and good for your price."),
  ("Furniture and appliance removal","The everyday residential work.")],
 "faqs":[
  ("Do you do commercial units as well as houses?","Yes. Small commercial and light industrial units are routine here, including after hours if you need the business open during the day."),
  ("Can you clear a workshop?","Yes, including benches, racking, tools and scrap. Tell us if there is machinery that needs more than two people to move."),
  ("Do you provide a certificate of insurance?","Yes. Most commercial landlords require one, so ask early and give us the certificate holder details."),
  ("Is there a trip fee?","No."),
  ("Can you take fluids and chemicals from a workshop?","No. Oils, solvents, fuels and industrial chemicals need proper disposal through a licensed handler. We will identify what we cannot take before quoting."),
  ("Do you take scrap metal?","Yes, and gladly. It recycles cleanly and a metal-heavy load usually helps your price."),
  ("What about a residential estate cleanout?","Yes. We work at your pace, set aside anything you want kept, and can get you a donation receipt."),
  ("Can you come after hours for a commercial job?","Yes. Tell us the window and we will size the crew to finish inside it."),
  ("How is it priced?","By truck volume for general material, by weight for heavy material like concrete. You get the number before we load.")],
 "nearby":["belle-isle","conway","azalea-park","meadow-woods"],
},
{
 "slug":"celebration","name":"Celebration","drive":"About 25 minutes","zips":"34747",
 "blurb":"Junk removal in Celebration, worked around the town's architectural rules and alley-load garages.",
 "intro":[
  "Celebration has the strictest appearance standards of anywhere we serve. Nothing is supposed to be visible from the street that should not be, and that is enforced.",
  "It also has alley-loaded garages and narrow rear lanes across much of the town, which changes how we park and carry. We plan that before we arrive rather than discovering it.",
  "Nothing goes to a curb here, ever. We carry from the property straight into the truck."],
 "hoods":["North Village","South Village","West Village","East Village","Artisan Park","Roseville Corner"],
 "angle_h":"What Celebration calls us for",
 "angle":[
  ("Removal with nothing left outside","The main reason people here call rather than waiting on a collection day."),
  ("Alley-access garage cleanouts","Rear-loaded garages and narrow lanes, which we plan the approach for."),
  ("Furniture replacement","Including from upper floors in townhomes with tight stairwells."),
  ("Rental and second-home turnovers","A significant share of Celebration property is not owner-occupied year round.")],
 "faqs":[
  ("Celebration has strict appearance rules. Is that a problem?","No, because nothing we do involves leaving anything visible. We carry from inside the property directly into the truck and leave with it in the same visit."),
  ("Can your truck get down the rear alleys?","Usually, with planning. Some lanes are tight. Tell us if you are alley-loaded and send a photo of the access if you are unsure."),
  ("Do you need to register with the town or the HOA?","For a normal removal, no. Anything involving demolition or equipment may require contractor registration, so check with the association first if your job involves a structure."),
  ("Is there a trip fee for Celebration?","No. It is about twenty-five minutes and pricing is the same as everywhere else."),
  ("Can you handle a townhome with narrow stairs?","Yes. Stairs are included and we bring enough crew. Tell us the floor and whether the stairwell turns."),
  ("Do you work with property managers on second homes?","Yes. Access details in advance, photos when done, no need for anyone to be on site."),
  ("Can you come on short notice?","We will try. Same-day this far out is not guaranteed, and we will give you an honest earliest time rather than a hopeful one."),
  ("Do you take patio furniture?","Yes. Sun-destroyed patio sets are one of the most common items in this part of the service area."),
  ("What cannot be taken?","Paint, solvents, fuel, propane, pool chemicals and pesticides. We will flag anything in your pile before quoting.")],
 "nearby":["kissimmee","hunters-creek","lake-nona","st-cloud","buenaventura-lakes"],
},
{
 "slug":"buenaventura-lakes","name":"Buenaventura Lakes","drive":"About 22 minutes","zips":"34743",
 "blurb":"Junk removal in Buenaventura Lakes, dense residential streets and homes that have been lived in hard.",
 "intro":[
  "Buenaventura Lakes is dense, established Osceola County residential, mostly built from the eighties onward, with a lot of multi-generational households and a significant rental share.",
  "The work here is everyday junk removal: furniture, appliances, garages and turnovers. Streets are narrow and driveways short, so we plan the park and carry rather than assume we can back in."],
 "hoods":["Buenaventura Lakes","Robert McLane area","Boggy Creek side","Simpson Road corridor","Lakeside"],
 "angle_h":"What Buenaventura Lakes calls us for",
 "angle":[
  ("Furniture and appliance removal","The most common call, often multiple items at once."),
  ("Rental turnovers","A substantial rental population and regular move-out clearing."),
  ("Garage and yard cleanouts","Established homes with accumulated material inside and out."),
  ("Multi-item single visits","Households clearing several things at once rather than one item.")],
 "faqs":[
  ("Is there a trip fee?","No. Buenaventura Lakes is about twenty-two minutes from our base."),
  ("Can your truck fit on a narrow street?","Usually. Where driveways are short or streets are tight we park where we can legally fit and carry from there, and that does not change your price."),
  ("Do you take several items in one visit?","Yes, and it is almost always cheaper than booking separate trips. Tell us everything when you call so the quote covers it all."),
  ("Do you handle rental move-outs?","Yes. Give us the deadline and we work to it, with photos when the unit is clear."),
  ("Can you do same day?","Sometimes. It is a little further out than Lake Nona, so we will give you an honest answer rather than a hopeful one."),
  ("Do you take appliances?","Yes. Refrigerators and freezers go through a certified recycler so the refrigerant is recovered."),
  ("Do I need to be home?","Not always. Access details and a photo of what goes is often enough, and we confirm by text before loading."),
  ("Do you take yard waste?","Yes, cut to manageable lengths. Whole standing trees need a tree service."),
  ("What is the minimum job?","A single item. There is a floor because a truck still has to drive out, but one item costs a fraction of a full load.")],
 "nearby":["kissimmee","celebration","st-cloud","meadow-woods","hunters-creek"],
},
{
 "slug":"waterford-lakes","name":"Waterford Lakes","drive":"About 22 minutes","zips":"32828, 32826",
 "blurb":"Junk removal in Waterford Lakes and east Orlando, including student rental turnovers near UCF.",
 "intro":[
  "Waterford Lakes and the surrounding east Orlando neighbourhoods sit close to UCF, and that shapes the calendar. Rental turnover here spikes hard around the end of the academic year, when a lot of units empty at once and furniture gets abandoned in volume.",
  "Outside that, it is a mix of nineties and two-thousands family housing now reaching the age where garages are full and original appliances are failing."],
 "hoods":["Waterford Lakes","Avalon Park","Eastwood","Stoneybrook East","Timber Springs","UCF area"],
 "angle_h":"What Waterford Lakes calls us for",
 "angle":[
  ("Student rental turnovers","End-of-semester clearing, often several units at once and on a tight window."),
  ("Abandoned furniture","Mattresses, sofas and desks left behind in rentals, which is the single most common item here."),
  ("Family home garage cleanouts","Housing from the nineties and two-thousands reaching peak garage accumulation."),
  ("Appliance replacement","Original builder appliances failing across the community at similar ages.")],
 "faqs":[
  ("Do you handle student rental turnovers?","Yes, and we know the calendar. End of semester is the busy window here and it books out, so call early rather than the week it happens."),
  ("Can you clear several units at once?","Yes. Give us the addresses, access details and the deadline, and you get photo confirmation per unit."),
  ("Do you take abandoned mattresses?","Yes, and it is the most common item in this area. Tell us the count."),
  ("What about tenant property left behind?","Florida law sets out a process for handling personal property left after a tenancy ends. Confirm the correct procedure with your attorney or property manager before anything is removed. We cannot make that call for you."),
  ("Is there a trip fee?","No. Waterford Lakes is about twenty-two minutes out."),
  ("Can you do a garage cleanout here?","Yes, and it is the other half of our work in this area. Send photos for an accurate number."),
  ("Do you work with property management companies?","Yes. One contact, multiple properties, documentation on each."),
  ("Can you come same day?","Sometimes, depending on the day. Outside the end-of-semester rush it is more likely."),
  ("Do you take electronics?","Yes. Televisions, monitors and computers go to an e-waste recycler rather than the landfill.")],
 "nearby":["azalea-park","conway","lake-nona","belle-isle"],
},
]
