# Blog posts. Each targets a real informational query. Where a post would need a
# specific local rule, fee or statistic, it teaches the reader how to check the
# current source rather than stating a number that may be wrong by next year.
# Author notes marked AUTHOR: are HTML comments and never render as text.

POSTS = [
{
 "slug":"how-much-does-junk-removal-cost-in-orlando","mt":'How Much Does Junk Removal Cost in Orlando?',"date":"2026-09-18",
 "title":"How Much Does Junk Removal Cost in Orlando? What Actually Drives the Price",
 "desc":"Junk removal is priced by truck volume, not by the item. Here is what moves the number up or down, and how to get a quote that does not change on the day.",
 "read":"6 min",
 "intro":[
  "Almost everyone asks the same first question, and almost every answer online dodges it. So here is the honest version: nobody can tell you what your job costs without knowing how much of a truck it fills.",
  "That is not evasion, it is how the industry prices. Understanding why makes it much easier to spot a quote that is going to change on the day."],
 "sections":[
  ("Volume, not item count","Junk removal is priced by the fraction of the truck your load fills. A quarter load, a half load, a full load. This is why a single sofa and twelve bags of clothing can cost about the same: they take up similar space.",
   "It also explains something that surprises people. Ten heavy boxes of books often cost less than one wardrobe, because the boxes stack and the wardrobe does not.",None),
  ("The four things that actually move the price","Volume is the base. Four things adjust it.",None,
   ["<strong>Weight.</strong> Concrete, tile, dirt and roofing shingles hit a truck's weight limit long before they fill its space. These are quoted by weight, not volume.",
    "<strong>Disposal surcharges.</strong> Some items cost money to dispose of regardless of size. Tires, mattresses, refrigerant appliances and electronics usually carry a fee at the facility, which gets passed through.",
    "<strong>Labor and access.</strong> Not stairs, which should be included. But a long carry from a back yard, a narrow gate, or an item that has to be dismantled before it will fit through a door all take time.",
    "<strong>Disassembly.</strong> Sheds, hot tubs, decking and playsets are demolition before they are hauling, and that is priced differently from carrying a finished item out of a room."]),
  ("What should already be included","Be suspicious of a quote that treats these as extras, because they are standard:",None,
   ["All labor and loading. You should not be lifting anything.",
    "Stairs and second or third floor carries.",
    "Disposal fees for ordinary household material.",
    "Sweeping up the space that was cleared."]),
  ("How to get a quote that does not change","Photos. Every time.",
   "A phone description of a garage is always optimistic, in good faith, by everyone. Photos of the actual pile take five minutes and turn a rough guess into a number that holds. If a company will not look at photos before quoting, that is worth noticing.",None),
  ("What to ask before you book","Four questions separate a straight operator from one that will surprise you:",None,
   ["Is the price you just gave me the price I pay, or an estimate?",
    "What is in the pile that you cannot take?",
    "Are stairs and the carry included?",
    "Where does the material actually go?"]),
 ],
 "takeaway":"Send photos, get a number before anything is loaded, and ask what in your pile cannot be taken. Those three steps eliminate almost every unpleasant surprise in this industry.",
 "related":["what-junk-removal-companies-will-not-take","where-does-your-junk-actually-go","garage-cleanout-in-a-weekend"],
},
{
 "slug":"what-junk-removal-companies-will-not-take","mt":'What Junk Removal Companies Will Not Take',"date":"2026-09-11",
 "title":"What Junk Removal Companies Will Not Take, and Where It Has to Go Instead",
 "desc":"Paint, fuel, propane, chemicals and asbestos cannot legally ride in a junk truck. Here is the full list and what to do with each one.",
 "read":"5 min",
 "intro":[
  "This is the part of the job that generates the most friction, and almost all of it is avoidable. A crew arrives, quotes the pile, and then has to explain that a third of it cannot legally go in the truck.",
  "None of this is a company being difficult. Hauling hazardous material without the right licensing is illegal, and the facilities we tip at will reject a load that contains it."],
 "sections":[
  ("The hard no list","These cannot go in a standard junk removal truck anywhere in Florida:",None,
   ["Liquid paint, stains, solvents and thinners","Gasoline, diesel, motor oil and other fuels","Propane tanks, including the small camping ones","Pesticides, herbicides and pool chemicals","Car and marine batteries","Asbestos-containing material","Medical waste and sharps","Ammunition, flares and explosives","Anything actively leaking or of unknown contents"]),
  ("Where each one actually goes","Household hazardous waste is the answer for most of this list. Orange and Osceola counties both run collection programs for residents, and they are typically free for household quantities.",
   "Paint is the common exception with an easy fix. Fully dried or empty cans are no longer hazardous and can go with ordinary debris. Small amounts dry out quickly if you stir in cat litter or sawdust and leave the lid off. A gallon of liquid paint is a problem. A gallon of solid paint is a can.",None),
  ("Propane is the one people forget","Small green camping cylinders end up in garage cleanouts constantly and they are genuinely dangerous in a compactor. Larger grill tanks can usually be exchanged or returned at a retailer that sells them. Neither belongs in a truck full of furniture.",None,None),
  ("Asbestos: the one worth taking seriously","If your house was built before about 1980, asbestos may be present in floor tile and the adhesive under it, pipe insulation, ceiling texture, and some siding and roofing.",
   "Intact and undisturbed, it is generally not a hazard. Broken, cut or torn out, it is. It needs testing first, and if positive, a licensed abatement contractor. Any hauler who offers to just take it is putting their crew and your household at risk, and you should not let them.",None),
  ("The grey areas worth asking about","These are usually fine but tell the company up front, because they carry facility fees or handling requirements:",None,
   ["Tires. Usually accepted, almost always with a per-tire fee. Give a count when you book.",
    "Refrigerators, freezers and AC units. Fine, but refrigerant has to be recovered by a certified recycler first.",
    "Electronics and CRT televisions. Accepted, routed to e-waste rather than landfill.",
    "Mattresses with bed bugs. Say so in advance. It changes the handling, not the answer."]),
 ],
 "takeaway":"Walk your pile before the truck arrives and pull out anything liquid, pressurised, chemical or from a pre-1980 renovation. Twenty minutes of sorting prevents the most common bad surprise on the day.",
 "related":["how-much-does-junk-removal-cost-in-orlando","garage-cleanout-in-a-weekend","where-does-your-junk-actually-go"],
},
{
 "slug":"hurricane-debris-cleanup-central-florida","mt":'Hurricane Debris Cleanup in Central Florida',"date":"2026-09-04",
 "title":"Hurricane Debris Cleanup in Central Florida: What the County Takes and What It Does Not",
 "desc":"After a storm, county debris collection covers less than most people assume. Here is the split, and how to avoid waiting weeks for a pickup that was never coming.",
 "read":"6 min",
 "intro":[
  "After a named storm, Central Florida counties usually run a special debris collection. It is genuinely useful and it is also narrower than people expect, which is how a pile sits at a curb for three weeks before somebody realises it was never on the list.",
  "The distinction that matters is between storm-generated debris and everything else."],
 "sections":[
  ("What county storm collection generally covers","Post-storm passes are typically limited to debris the storm itself created, separated into categories:",None,
   ["Vegetative debris: limbs, branches, palm fronds, trunks","Construction and demolition debris from storm damage: fence sections, roofing, siding, drywall from flooding",
    "Sometimes white goods: appliances ruined by flooding, handled separately because of refrigerant",
    "Sometimes household hazardous waste, also separated"]),
  ("What it does not cover","This is where people get caught. Normal household junk that happened to be put out at the same time is not storm debris, and crews will drive past it.",
   "Furniture from a garage that did not flood, an old mattress, construction debris from a renovation that predates the storm, and anything in bags or boxes generally does not qualify. Several counties explicitly exclude bagged material because crews use grapple trucks that cannot handle bags.",None),
  ("Separate your piles or lose the pickup","The single most common mistake is one mixed pile. Grapple trucks make separate passes for separate categories. A pile of branches with a sofa in the middle of it is not a vegetative pile any more, and it may get skipped entirely on every pass.",
   "Keep vegetative separate from construction debris, keep appliances separate, keep hazardous separate, and keep it all out of the road and away from meters, hydrants and low lines.",None),
  ("How long it actually takes","First passes in hard-hit areas often run weeks after the storm, and a full sweep can take a month or more. If you can live with the pile, waiting is free and is genuinely the right call for a big vegetative pile.",
   "Hiring a hauler makes sense for the things the county will not take, for anything that is a hazard or a mosquito breeding site where it sits, and for rentals and businesses that cannot wait.",None),
  ("Before the next storm","The cheapest debris cleanup is the one you avoid. Clearing a garage of what you were going to get rid of anyway means less to become debris, and it means the garage can hold the patio furniture when the next warning comes.",None,None),
 ],
 "takeaway":"Separate your piles by category, keep bagged and boxed material out of them, and understand that anything not created by the storm is yours to handle. Check your own county's current guidance after every storm, because the rules and the categories change per event.",
 "related":["what-junk-removal-companies-will-not-take","garage-cleanout-in-a-weekend","shed-and-fence-removal-after-a-storm"],
},
{
 "slug":"where-does-your-junk-actually-go","mt":'Where Does Your Junk Actually Go?',"date":"2026-08-28",
 "title":"Where Does Your Junk Actually Go? Donation, Recycling and Landfill in Central Florida",
 "desc":"Every hauler says they donate and recycle. Here is what actually happens to each category of material, and the questions that tell you whether a company means it.",
 "read":"5 min",
 "intro":[
  "Every junk removal company on earth says it donates and recycles. It is the easiest claim in the industry to make and one of the easier ones to check.",
  "Here is what genuinely happens to each category, and what to ask if you want to know whether a company is actually doing it."],
 "sections":[
  ("Metal is the easy one","Appliances, bed frames, filing cabinets, fencing, mowers and general scrap are mostly steel. Steel has real scrap value, so recycling it is both better environmentally and cheaper than landfilling it.",
   "If a company tells you metal goes to the landfill, they are either lying or losing money on purpose.",None),
  ("Furniture depends entirely on condition","This is where claims get soft. Donation partners are charities running thrift operations, not disposal services. They can only take furniture they can sell.",
   "Clean, structurally sound, no rips, no heavy staining, no smoke damage, no pests. A sofa that has been in a damp garage for three years will be refused, and a hauler who promises it will be donated is telling you what you want to hear.",None),
  ("Mattresses are more recyclable than people think","A mattress separates into steel springs, foam and fibre, all of which have a downstream use. A dry, clean mattress can be genuinely recycled.",
   "A soaked, mouldy or infested one cannot, and will be landfilled. This is another reason not to leave one at a curb in Florida through an afternoon thunderstorm.",None),
  ("Electronics have their own stream","Televisions, monitors and computers contain both recoverable material and things you do not want in a landfill. CRT televisions in particular contain leaded glass. These go to e-waste processors, not general waste.",None,None),
  ("Cardboard, paper and yard waste","Flattened cardboard from a move is clean recyclable material and one of the better outcomes in the whole business. Yard waste is typically composted or mulched rather than landfilled.",None,None),
  ("The questions that separate claim from practice","If this matters to you, ask directly:",None,
   ["Which donation partners do you actually use? A real answer names organisations.",
    "Can you get me a donation receipt? A company genuinely donating can.",
    "What percentage of a typical load ends up in the landfill? An honest answer is a range, not zero.",
    "What happens to my refrigerator's refrigerant? The answer should involve a certified recycler."]),
 ],
 "takeaway":"Metal and cardboard are recycled because it is economically sensible. Furniture donation depends on condition, and any company promising to donate a damaged sofa is not being straight with you.",
 "related":["how-much-does-junk-removal-cost-in-orlando","what-junk-removal-companies-will-not-take","mattress-disposal-in-orlando"],
},
{
 "slug":"mattress-disposal-in-orlando","mt":'Mattress Disposal in Orlando',"date":"2026-08-21",
 "title":"Mattress Disposal in Orlando: Why the Curb Is Not an Option",
 "desc":"Standard trash will not take a mattress, HOAs cite you for leaving one out, and Florida rain ruins it within hours. Here are the options that actually work.",
 "read":"4 min",
 "intro":[
  "The mattress is the classic stuck item. It is too big for regular collection, too awkward for a car, and it is the single most cited item in HOA and code enforcement complaints about curbside junk.",
  "There are four real options and one that does not work."],
 "sections":[
  ("Why the curb fails","Three reasons, and they compound.","Standard residential trash collection will not take a mattress. In an HOA community or an incorporated city like Belle Isle, leaving one out can get you a violation notice. And a mattress left outside through one Florida afternoon storm absorbs an enormous amount of water, doubling in weight and ruling out recycling entirely.",None),
  ("Option one: bulk pickup, if your service offers it","Some residential waste services include a limited number of bulk item pickups per year, usually scheduled in advance with a specific item limit.",
   "Check your provider's current terms directly rather than relying on what a neighbour told you, because these programs change and they vary between municipalities in this area.",None),
  ("Option two: take it to a transfer station yourself","Possible if you have a truck and a free morning. Expect a disposal fee specifically for mattresses at most facilities, and check the hours and what they accept before you drive out with one strapped to a roof.",None,None),
  ("Option three: retailer haul-away on delivery","If the mattress is being replaced, the retailer will often take the old one when they deliver the new one, sometimes free and sometimes for a fee.",
   "This is the cheapest option by a distance and the one people most often forget to ask about. Ask before you buy, not after delivery is scheduled.",None),
  ("Option four: a hauler","Worth it when the mattress is not being replaced, when there are several, when it is upstairs, or when it needs to go today. A hauler takes it from the bedroom rather than the curb, which is the actual hard part of the job.",None,None),
  ("If there are bed bugs, say so","Not disclosing this is a genuine problem. An infested mattress carried unwrapped through a house and loaded into a truck with other people's furniture spreads the problem.",
   "Tell whoever is taking it. It changes how the item is bagged and handled and where it can go. It does not usually change whether they will take it.",None),
 ],
 "takeaway":"If you are buying a replacement, ask the retailer to haul the old one on delivery. It is almost always the cheapest route and it is the one most people miss.",
 "related":["where-does-your-junk-actually-go","how-much-does-junk-removal-cost-in-orlando","rental-turnover-cleanouts"],
},
{
 "slug":"garage-cleanout-in-a-weekend","mt":'Garage Cleanout in a Weekend: A Plan',"date":"2026-08-14",
 "title":"Garage Cleanout in a Weekend: A Plan That Actually Finishes",
 "desc":"Most garage cleanouts stall because of sorting, not lifting. Here is a two-day plan built around that, including what to pull out before a hauler arrives.",
 "read":"6 min",
 "intro":[
  "Garage cleanouts fail for a predictable reason. People start by opening boxes, get absorbed in the contents, and four hours later the garage is worse than when they began because everything is now on the driveway.",
  "The fix is to decide the rule before you touch anything, then apply it without reopening the decision."],
 "sections":[
  ("Saturday morning: decide the rule first","Before anything moves, write down what earns a place in this garage. Vehicles, lawn equipment, tools you used in the last two years, holiday decorations, sports gear in active use.",
   "Everything else is leaving unless there is a specific reason it stays. Having the rule written down means you are applying a decision rather than making a hundred new ones.",None),
  ("Saturday: four zones, no fifth","Mark four areas with tape or boxes. Keep. Donate. Hazardous. Gone.",
   "There is no maybe pile. The maybe pile is where garage cleanouts go to die, because it gets put back in the garage at the end of the weekend and you have achieved nothing.",None),
  ("Saturday afternoon: pull the hazardous material out now","Do this before you book anyone, because no hauler can take it and finding out on the day wastes everyone's time. Into the hazardous zone:",None,
   ["Liquid paint, stain, solvent and thinner","Gasoline, oil and fuel cans","Propane tanks including small camping cylinders","Pesticides, herbicides and pool chemicals","Car batteries","Anything unlabelled or leaking"]),
  ("Saturday evening: dry out the paint","Small amounts of leftover paint can be turned into ordinary waste. Stir in cat litter or sawdust, leave the lid off overnight, and by morning it is solid. A solid can is just a can.",
   "Larger quantities are not worth the effort. Take them to household hazardous waste collection with the rest.",None),
  ("Sunday morning: photograph the Gone pile and book","Photos get you an accurate quote. A verbal description of a garage pile is optimistic every single time, from everybody, without exception.",
   "Take four or five shots from different angles, including anything unusually heavy or awkward, and send them with the quote request.",None),
  ("Sunday: the donation run","Do this yourself if you have a vehicle, because it is the part a hauler adds the least value to. Clean, working, sellable items only. A charity is not a disposal service and cannot take a broken exercise bike.",None,None),
  ("What to ask the hauler","Three things before they load:",None,
   ["Is that the final price or an estimate?",
    "Is there anything in this pile you cannot take?",
    "Do you sweep up?"]),
 ],
 "takeaway":"The lifting is not the hard part and it is the part you can pay someone to do. Sorting is the hard part, and the only way through it is deciding the rule before you start and refusing to build a maybe pile.",
 "related":["what-junk-removal-companies-will-not-take","how-much-does-junk-removal-cost-in-orlando","estate-cleanout-checklist"],
},
{
 "slug":"estate-cleanout-checklist","mt":'Estate Cleanout Checklist',"date":"2026-08-07",
 "title":"Estate Cleanout Checklist: Clearing a Home After a Loss",
 "desc":"A practical order of operations for emptying a family home, including what to find before anything is hauled and how to handle disagreement between family members.",
 "read":"7 min",
 "intro":[
  "Clearing a parent's house is not a junk removal problem with a sad backdrop. It is a family and legal process that happens to end with a truck.",
  "This is the order that causes the fewest regrets, from people who have been through it."],
 "sections":[
  ("Before anything moves: find the paperwork","Go through the house once looking only for documents. Nothing gets thrown out, donated or sold until this is done.",None,
   ["Will, trust documents and any letter of instruction","Deeds, titles for vehicles and boats","Insurance policies, including life and burial","Bank, investment and retirement statements","Tax returns for the last several years","Social Security and pension correspondence","Safe deposit box keys and any records of one","Military discharge papers, which affect burial benefits"]),
  ("Then the places people hide things","An older generation that kept cash and valuables at home hid them in predictable places. Check all of them before a single box leaves:",None,
   ["Inside books, especially a row of them on a shelf","Taped under drawers and inside drawer cavities","Freezer, and inside food containers in it","Coat and suit pockets, and inside shoes","Under mattresses and inside pillowcases","Medicine cabinets and toilet tanks","Behind picture frames and inside frame backing","Toolboxes, paint cans and coffee tins in the garage"]),
  ("Photographs before furniture","Photographs, letters and home video are the things families actually regret losing, and they are the least likely to look valuable to someone clearing a room quickly.",
   "Box every photograph and every piece of correspondence and set it aside. Sorting can happen later, somewhere else, when nobody is working to a deadline.",None),
  ("Let each person name a small number of items","Disagreement over possessions is usually about meaning rather than money. A structure that works: each person privately lists a small number of items that matter to them, then the lists are compared.",
   "Most of the time the lists barely overlap, because people want different things for different reasons. The few genuine conflicts can then be handled one at a time instead of as a general argument.",None),
  ("Get an appraisal before assuming anything is worthless","Two categories catch people out. Things assumed valuable that are not, like most mass-market china, most collectible plates and most furniture from the eighties.",
   "And things assumed worthless that are not: mid-century furniture, tools, certain costume jewellery, vinyl records, cameras and militaria. If a house has a lot of any of these, an appraiser costs far less than what gets thrown away without one.",None),
  ("Then, and only then, clear the house","Once documents, photographs, keepsakes and anything appraised are out, the rest is volume. This is the part to hand off.",
   "Expect multiple truckloads for a full house with a garage and attic. Ask for a donation receipt for what goes to charity, since it may matter for the estate's taxes.",None),
  ("What cannot be hauled","Older homes accumulate exactly the material no hauler can take. Expect to find and separately dispose of:",None,
   ["Paint, solvents and garage chemicals","Old fuel and propane cylinders","Pesticides, some of them long banned","Firearms and ammunition, which have their own legal process","Prescription medication, which goes to a pharmacy take-back","Asbestos material in a pre-1980 house, which needs testing first"]),
 ],
 "takeaway":"Documents first, then hiding places, then photographs, then keepsakes, then appraisal, then the truck. Doing it in that order is the difference between a hard week and a permanent regret.",
 "related":["garage-cleanout-in-a-weekend","what-junk-removal-companies-will-not-take","where-does-your-junk-actually-go"],
},
{
 "slug":"rental-turnover-cleanouts","mt":'Rental Turnover Cleanouts in Orlando',"date":"2026-07-31",
 "title":"Rental Turnover Cleanouts: Getting a Unit Guest-Ready on a Deadline",
 "desc":"A practical guide for landlords and property managers in Orlando, Kissimmee and St. Cloud on clearing a unit between tenants or guests without losing days.",
 "read":"5 min",
 "intro":[
  "A vacant unit costs money every day it stays vacant, and in the short-term rental corridor around Kissimmee the gap between guests can be hours rather than days.",
  "The operators who handle this well are not faster on the day. They are better organised before it."],
 "sections":[
  ("Long-term turnover versus short-term turnover","These are genuinely different jobs.",
   "A long-term tenant move-out leaves behind whatever they abandoned, and you usually have a few days. A short-term rental turnover is about replacing worn furniture and clearing damage inside a booking gap, often on a fixed clock with a guest arriving.",None),
  ("Know your abandoned property obligations","Before you dispose of anything a departed long-term tenant left, understand that Florida law sets out a process for handling personal property left behind after a tenancy ends, including notice requirements and waiting periods.",
   "This is not optional and it is not something a hauler can advise you on. Talk to your attorney or property management company about the correct procedure for your situation before you clear a unit. Getting it wrong is expensive in a way that dwarfs the cost of the cleanout.",None),
  ("Book before the tenant leaves, not after","The single biggest scheduling win. If you know the move-out date, book the clearout for the day after rather than calling once you have walked the unit and seen the mess.",
   "Same-day availability is real but not guaranteed, and a unit sitting for two days waiting on a truck costs more than the cleanout.",None),
  ("Photograph everything before it moves","For the security deposit, for an insurance claim, and for your own protection. Photograph the unit on arrival, before anything is touched.",
   "Then have whoever clears it photograph the empty unit when they finish. That pair of photo sets settles almost every dispute before it starts.",None),
  ("The items that come up every time","Turnover cleanouts are remarkably repetitive. Expect:",None,
   ["Mattresses, which almost always need replacing on a schedule anyway",
    "Sun-destroyed patio furniture, especially in vacation rentals",
    "Damaged case goods: dressers, nightstands, coffee tables",
    "Whatever is in the garage or storage closet, which the tenant never mentioned",
    "Abandoned food and cleaning chemicals, which need separating out"]),
  ("Coordinate delivery and removal in the right order","When furniture is being replaced, clear the old set before the new one arrives, not after.",
   "Getting this backwards leaves two sets of furniture in a property with nowhere to put either, and turns a two-hour job into a day. Give both the delivery window and the removal window to whoever is doing the removal.",None),
  ("If you run several properties, use one contact","Managers with multiple units get better scheduling by consolidating. One point of contact, addresses and access details in advance, photo confirmation per unit so you are not driving out to verify.",None,None),
 ],
 "takeaway":"Book before the tenant leaves, photograph before and after, sequence removal ahead of delivery, and get legal advice on abandoned property rather than guessing at the process.",
 "related":["mattress-disposal-in-orlando","how-much-does-junk-removal-cost-in-orlando","moving-out-of-a-lake-nona-apartment"],
},
{
 "slug":"moving-out-of-a-lake-nona-apartment","mt":'Moving Out of a Lake Nona Apartment',"date":"2026-07-24",
 "title":"Moving Out of a Lake Nona Apartment: What to Do With What Is Left",
 "desc":"Getting a deposit back means an empty unit, and Lake Nona's HOA and apartment rules make the curb a bad plan. Here is the sequence that works.",
 "read":"4 min",
 "intro":[
  "Every move ends with the same pile: furniture that will not fit the new place, a mattress not worth moving, and a mountain of flattened boxes.",
  "In Lake Nona that pile has nowhere obvious to go, because both the apartment complexes and the HOA communities have real rules about what can sit outside."],
 "sections":[
  ("The curb is not available here","Most Lake Nona communities restrict what can be left outside and for how long, and enforcement is genuinely active in a way it is not everywhere.",
   "Apartment dumpsters are for household trash. Putting a sofa beside one typically gets the cost of removing it billed to your unit, which comes out of the deposit you are trying to protect.",None),
  ("Start with what is actually worth something","Two weeks before the move, not two days. Anything sellable takes time to sell.",
   "After that window closes, switch from selling to donating. Holding a dresser for another week hoping for a buyer is how people end up with a full apartment on move-out day.",None),
  ("Donate what is clean and sound","Charities can take furniture they can sell: clean, structurally sound, no rips or heavy staining. They cannot take a water-damaged particleboard bookshelf, and asking them to absorb a disposal cost is not a donation.",
   "Several organisations in the Orlando area will collect larger furniture. Book that collection early, because the good ones schedule out.",None),
  ("Cardboard is its own problem","A one-bedroom move generates a startling volume of cardboard. Flattened, it compresses well and it is clean recyclable material.",
   "Check whether your complex has a dedicated cardboard recycling area before you assume it does. Many do, and a stack beside a dumpster that has one is a violation rather than a recycling attempt.",None),
  ("Book the last pass before your final walkthrough","Whatever is left after selling and donating needs to be gone before the walkthrough, not after.",
   "Schedule it for the morning of, or the day before. A hauler takes it from inside the unit, which is the whole point. You do not carry anything down to a curb that will not accept it anyway.",None),
 ],
 "takeaway":"Sell early, donate what is clean, recycle the cardboard properly, and have anything left taken from inside the unit before your final walkthrough rather than after.",
 "related":["rental-turnover-cleanouts","mattress-disposal-in-orlando","where-does-your-junk-actually-go"],
},
{
 "slug":"shed-and-fence-removal-after-a-storm","mt":'Shed and Fence Removal After a Storm',"date":"2026-07-17",
 "title":"Shed and Fence Removal After a Storm: What to Do First",
 "desc":"A damaged shed or downed fence is a safety and insurance problem before it is a cleanup problem. Here is the order that protects your claim.",
 "read":"5 min",
 "intro":[
  "Florida storms take out sheds and fences more than almost anything else, and the instinct afterwards is to start clearing immediately.",
  "Slow down for one afternoon. What you do in the first day affects whether your insurance pays for any of it."],
 "sections":[
  ("Photograph before you touch anything","This is the step people skip and regret. Photograph the damage from multiple angles, wide and close, before anything is moved.",
   "An adjuster cannot assess damage that has already been hauled away. If you clear first and claim second, you are relying on their goodwill and your description.",None),
  ("Call your insurer before you hire anyone","Ask two questions: is this covered, and do you need to inspect before removal?",
   "Some policies cover detached structures and fencing, some do not, and some require an inspection before debris is cleared. Find out which yours is before a truck arrives.",None),
  ("Make it safe, and stop there","There is a difference between making a site safe and clearing it. Safe means no exposed nails or sharp metal where people walk, nothing that will blow into a neighbour's property in the next storm, and no standing water collecting where mosquitoes will breed.",
   "Tarp it, tape it off, secure the loose pieces. Then leave the rest until you have the insurance answer.",None),
  ("Storm debris versus ordinary debris","If your county is running post-storm collection, storm-damaged fencing and shed material usually qualifies as construction and demolition debris, which is collected separately from vegetative debris.",
   "What does not qualify is everything that was inside the shed. Contents are ordinary household junk regardless of the storm, and mixing them into a debris pile can get the whole pile skipped.",None),
  ("The contents are usually the hazardous part","Sheds store exactly what cannot be hauled: fuel cans, pesticides, pool chemicals, old paint, propane cylinders.",
   "After a storm these are often damaged or leaking, which makes them more urgent and more dangerous. Separate them, do not let them sit in standing water, and take them to household hazardous waste collection.",None),
  ("Rebuild permits are a separate question","Removing a damaged accessory structure and building a new one are different from a permitting standpoint, and requirements vary between Orange County, Osceola County and incorporated cities like Belle Isle and St. Cloud.",
   "Check with your local building department before you commit to a rebuild. Nobody hauling debris can answer this for you.",None),
 ],
 "takeaway":"Photograph it, call your insurer, make it safe, and only then clear it. Reversing that order is how people end up paying out of pocket for damage that was covered.",
 "related":["hurricane-debris-cleanup-central-florida","what-junk-removal-companies-will-not-take","garage-cleanout-in-a-weekend"],
},
]

POSTS += [
{
 "slug":"how-to-get-rid-of-a-couch","date":"2026-09-24","mt":"How to Get Rid of a Couch in Orlando",
 "title":"How to Get Rid of an Old Couch: Every Option, Ranked by Cost",
 "desc":"Six ways to get rid of a sofa in Orlando, from free to paid, and which one actually fits your situation.",
 "read":"5 min",
 "intro":[
  "A couch is the classic stuck item. Too big for the car, too heavy for two people down a stairwell, and no standard trash service will take it.",
  "Here are the six real options, cheapest first, with the honest catch on each."],
 "sections":[
  ("Free: ask the retailer on delivery","If you are buying a replacement, ask whether they will haul the old one away when they deliver. Many will, free or for a small fee.",
   "This is the cheapest option by a distance and the one most people forget to ask about. Ask before you buy, not after delivery is booked.",None),
  ("Free: donate it, if it is actually donatable","Charities take furniture they can sell. That means clean, structurally sound, no rips, no heavy staining, no smoke damage, no pests.",
   "Several Orlando-area organisations collect larger furniture, but book early because collection slots fill. And be realistic: if it has been in a garage for two years, they will refuse it, and asking a charity to absorb a disposal cost is not a donation.",None),
  ("Free-ish: sell it, if you start early","Two weeks, not two days. Anything sellable takes time to sell, and a couch is a low-value, high-hassle listing.","After that window, switch to donating. Holding a sofa another week hoping for a buyer is how people end up with it still in the living room on moving day.",None),
  ("Cheap but work: take it to a transfer station","Possible if you have a truck and a free morning. Expect a disposal fee, check the hours, and understand that the hard part was never the driving.",
   "The hard part is getting a sectional out of a second-floor apartment without wrecking the stairwell.",None),
  ("Do not: leave it at the curb","In most Orlando-area HOAs and in incorporated cities like Belle Isle, this gets you a violation notice. At an apartment complex, the cost of removing it typically gets billed to your unit.",
   "It also rains here. A soaked couch is dramatically heavier and rules out donation entirely.",None),
  ("Paid: hire a hauler","Worth it when it is upstairs, when it will not fit back through the door it came in, when there are several items, or when it needs to be gone today.",
   "A single sofa is a small partial load, not a full truck, and it gets taken from the room rather than the curb.",None),
 ],
 "takeaway":"If you are replacing it, ask the retailer to take the old one on delivery. If you are not, decide between donating and hauling within two weeks, because the sofa is not going to get easier to move.",
 "related":["mattress-disposal-in-orlando","where-does-your-junk-actually-go","how-much-does-junk-removal-cost-in-orlando"],
},
{
 "slug":"junk-removal-vs-dumpster-rental","date":"2026-09-22","mt":"Junk Removal vs Dumpster Rental",
 "title":"Junk Removal or Dumpster Rental? An Honest Comparison",
 "desc":"We do not rent dumpsters, so here is a straight comparison of when each one is genuinely the better choice.",
 "read":"5 min",
 "intro":[
  "We are a junk removal company and we do not rent dumpsters, which means we have no reason to pretend a dumpster is never the right answer. Sometimes it clearly is.",
  "The deciding factor is not the size of the job. It is whether the debris already exists or is going to appear over time."],
 "sections":[
  ("Rent a dumpster when debris accumulates over days or weeks","A kitchen renovation, a roof, a long DIY project. Debris appears gradually and you need somewhere to put it as it does.",
   "Paying for a truck and crew to come out six times costs far more than one container sitting there for a week.",None),
  ("Hire a hauler when the debris already exists","A full garage, a house cleanout, a furniture replacement, a storm cleanup. It is all there right now and you want it gone today.",
   "With a hauler you pay for what actually gets hauled. With a dumpster you pay for the container whether you fill it or not.",None),
  ("The things people forget about dumpsters",None,None,
   ["<strong>You do the loading.</strong> Every item, by hand, including whatever is in the attic. This is the big one.",
    "<strong>Driveway damage.</strong> A loaded roll-off is heavy and can crack a residential driveway.",
    "<strong>Permits.</strong> If it goes on a public street rather than your property, many municipalities require one.",
    "<strong>HOA rules.</strong> Plenty of Orlando-area communities restrict how long a container can sit, or ban them outright.",
    "<strong>Weight limits.</strong> Overfill it and you pay overage, which surprises people on heavy material."]),
  ("The things people forget about haulers",None,None,
   ["<strong>You pay for volume, not time.</strong> If your pile is bigger than you thought, the price moves.",
    "<strong>Scheduling.</strong> The truck comes when it comes, not whenever you feel like loading.",
    "<strong>Multiple passes cost multiple trips.</strong> Which is exactly why a long project wants a container."]),
  ("A rough rule",
   "If you are going to be generating debris for more than about three days, rent a container. If the pile is already sitting there, hire someone to take it.",
   "And if you genuinely cannot load it yourself, a dumpster does not solve your problem no matter how long the project runs.",None),
 ],
 "takeaway":"Debris that appears over time wants a dumpster. Debris that already exists wants a hauler. If you cannot do the lifting, that decides it regardless.",
 "related":["how-much-does-junk-removal-cost-in-orlando","what-junk-removal-companies-will-not-take","construction-debris-disposal-in-florida"],
},
{
 "slug":"appliance-disposal-in-orlando","date":"2026-09-16","mt":"Appliance Disposal in Orlando",
 "title":"Appliance Disposal in Orlando: Why Your Old Fridge Is Harder Than You Think",
 "desc":"Refrigerant law, scrap value and retailer haul-away. Every route for getting rid of a fridge, washer or water heater.",
 "read":"5 min",
 "intro":[
  "Appliances look like they should be easy. They are metal, metal recycles, and there is scrap value in them. Then you discover nobody will take your refrigerator.",
  "The reason is refrigerant, and it is worth understanding because it determines which options are actually open to you."],
 "sections":[
  ("Why refrigerators are different","Refrigerators, freezers and air conditioners contain refrigerant, which cannot legally be released into the atmosphere. It has to be recovered by a technician before the unit can be scrapped or landfilled.",
   "That recovery step costs money, which is why many services that happily take a washing machine will refuse a fridge.",None),
  ("Route one: retailer haul-away on delivery","If you are replacing the appliance, ask the retailer to take the old one when they deliver. This is usually the cheapest route and it is built into their process.",
   "Ask before you buy. Once delivery is scheduled it is often too late to add.",None),
  ("Route two: utility rebate programs","Some utilities run appliance recycling programs that collect old working refrigerators and freezers, sometimes with a rebate, because an old inefficient second fridge in a garage costs real money to run.",
   "Availability and terms change, so check your own utility's current program directly rather than relying on what somebody told you last year.",None),
  ("Route three: scrap yard","Possible if you have a truck and the appliance has no refrigerant. Washers, dryers, ranges and water heaters are mostly steel and a yard will take them.",
   "Do not expect to get rich. The scrap value of a household appliance is modest and it will not cover a day off work.",None),
  ("Route four: a hauler","Worth it when the appliance is in a basement or upstairs, when there are several, when it has refrigerant, or when you simply do not have a truck.",
   "A hauler routes refrigerant units through a certified recycler and takes the metal ones to scrap.",None),
  ("Two safety points that matter",None,None,
   ["<strong>Gas appliances.</strong> A gas range or dryer needs the gas line capped by a licensed plumber before anyone moves it. No hauler should be cutting a gas line.",
    "<strong>Water heaters.</strong> Drain it first. A full one holds forty or more gallons and is genuinely dangerous to carry.",
    "<strong>Old fridges and children.</strong> If an old refrigerator is sitting somewhere waiting for pickup, remove the door. This is a real hazard and it takes ten minutes."]),
 ],
 "takeaway":"If you are replacing it, retailer haul-away is almost always cheapest. If not, refrigerant is what determines your options, and gas appliances need a plumber before anyone moves them.",
 "related":["where-does-your-junk-actually-go","what-junk-removal-companies-will-not-take","how-to-dispose-of-a-tv-in-florida"],
},
{
 "slug":"how-to-dispose-of-a-tv-in-florida","date":"2026-09-13","mt":"How to Dispose of a TV in Florida",
 "title":"How to Dispose of an Old TV in Florida Without Dumping It",
 "desc":"Televisions contain leaded glass and heavy metals, and most curbside services refuse them. Here are the real options.",
 "read":"4 min",
 "intro":[
  "Old televisions are one of the most commonly dumped items in Florida, and it is not because people are careless. It is because almost nothing will take them.",
  "Regular trash collection refuses them, thrift stores refuse the old ones, and they are too awkward for most people to haul themselves."],
 "sections":[
  ("Why it matters more than it looks","A CRT television, the heavy tube kind, contains several pounds of leaded glass in the screen. Flat screens contain circuit boards with heavy metals, and older LCD backlights can contain mercury.",
   "None of that belongs in the ground. It is also why e-waste processing costs money, which is the real reason so few services accept televisions.",None),
  ("Option one: retailer take-back","Some electronics retailers run take-back programs, occasionally free and occasionally with a fee depending on the item. Terms change, so check the current policy at the retailer rather than assuming.",None,None),
  ("Option two: county e-waste collection","Orange and Osceola counties both run electronics collection for residents as part of their household hazardous waste programs. This is often the cheapest legitimate route.",
   "Check your county's current schedule, location and accepted-items list directly before driving out with a television in the car.",None),
  ("Option three: donate it, if it actually works","A working flat screen from the last few years can sometimes be donated. A CRT cannot. Thrift operations stopped accepting tube televisions years ago because nobody buys them.",
   "Be honest with yourself about which one you have.",None),
  ("Option four: a hauler","Worth it for a wall-mounted set, a large or heavy unit, several at once, or an office clearing out its equipment.",None,None),
  ("Before you hand over a computer","Televisions do not store your data. Computers, laptops and some smart TVs do.",
   "Wipe or physically remove the drive before disposal. A hauler is not a certified data destruction service, and for business machines with sensitive data you want a certified ITAD provider, not a junk truck.",None),
 ],
 "takeaway":"Check your county's e-waste collection first, since it is usually the cheapest legitimate option. Never put a CRT television at the curb, and always wipe a computer before it leaves your house.",
 "related":["appliance-disposal-in-orlando","where-does-your-junk-actually-go","what-junk-removal-companies-will-not-take"],
},
{
 "slug":"clearing-a-house-before-selling","date":"2026-09-09","mt":"Clearing a House Before Selling",
 "title":"Clearing a House Before You Sell: What Actually Affects the Offer",
 "desc":"What to clear before listing photos, what buyers notice, and the one room sellers consistently ignore.",
 "read":"6 min",
 "intro":[
  "Decluttering before a sale is advice everyone has heard and most people apply unevenly. They stage the living room and leave the garage packed.",
  "Buyers notice space. Anything that makes a room read as smaller than it is costs you, and the rooms sellers ignore are exactly the ones buyers use to judge storage."],
 "sections":[
  ("Do it before the photographer, not after","Listing photos are the entire first impression and they are taken once. A house cleared after the photos were taken still shows online as a cluttered house for the whole listing.",
   "Whatever you are going to clear, clear it before the camera arrives.",None),
  ("The garage is the room sellers ignore","Buyers walk into a packed garage and conclude the house has no storage. It is the single most common self-inflicted wound in a residential sale.",
   "An empty garage reads as a large garage. A garage with a wall of boxes reads as a small one, regardless of the actual square footage.",None),
  ("Closets get opened","Every buyer opens closets, and a closet packed to the door says the house does not have enough storage. Aim to have closets look about two-thirds full.",
   "The same applies to the pantry and the linen cupboard.",None),
  ("Clear surfaces more than you think is necessary","Kitchen counters, bathroom vanities, dressers. Surfaces read as clutter in photographs even when the room is tidy in person.",None,None),
  ("What to do with what comes out",None,None,
   ["<strong>Keeping it?</strong> Off site. A storage unit for the listing period is cheaper than a lower offer.",
    "<strong>Selling it?</strong> Start early, because it takes longer than you think and you are on a deadline.",
    "<strong>Donating it?</strong> Clean and sound items only, booked in advance.",
    "<strong>Finished with it?</strong> A hauler, in one visit, before the photographer."]),
  ("Do not over-clear",
   "An entirely empty house shows badly too. Buyers struggle to judge scale in empty rooms, and every flaw in the walls and floors is fully exposed.",
   "Aim for lived-in and spacious, not stripped.",None),
  ("The deadline nobody plans for","If you are clearing and selling, book the removal for before the photos and keep a second slot for after the closing date is set.",
   "The week before a closing is the busiest week in this business and availability tightens.",None),
 ],
 "takeaway":"Clear before the listing photos, start with the garage and the closets, and put what you are keeping off site rather than shuffling it into another room.",
 "related":["garage-cleanout-in-a-weekend","estate-cleanout-checklist","how-much-does-junk-removal-cost-in-orlando"],
},
{
 "slug":"construction-debris-disposal-in-florida","date":"2026-09-02","mt":"Construction Debris Disposal in Florida",
 "title":"Construction Debris Disposal in Florida: What You Can and Cannot Throw Out",
 "desc":"Renovation debris rules, weight limits, asbestos in older homes, and when a dumpster beats a hauler.",
 "read":"6 min",
 "intro":[
  "Renovation generates more material than almost anyone plans for, and a surprising amount of it cannot go in a regular container.",
  "The two things that catch people out are weight and age: heavy material costs differently, and anything from a pre-1980 house may need testing before it is touched."],
 "sections":[
  ("Heavy material is priced by weight, not volume","Concrete, brick, tile, dirt and roofing shingles hit a truck or container's weight limit long before they fill its space.",
   "A quarter load of concrete can outweigh a full load of furniture. If a quote for heavy material is given by volume alone, expect it to change.",None),
  ("Asbestos: the one that genuinely matters","If the building predates roughly 1980, asbestos may be present in floor tile and the black adhesive beneath it, pipe insulation, ceiling texture, some siding and some roofing.",
   "Undisturbed, it is generally not a hazard. Cut, sanded or torn out, it is. It needs testing first and a licensed abatement contractor if positive. No legitimate hauler will take suspected asbestos material, and one who offers to is a reason to hire someone else.",None),
  ("Lead paint in older homes","Homes built before 1978 may have lead paint. Renovation that disturbs it has federal requirements around containment and the certification of the contractor doing the work.",
   "This is a contractor question rather than a disposal question, but it affects the debris and it is worth knowing before demolition starts.",None),
  ("What goes in ordinary debris",None,None,
   ["Drywall, plaster and insulation","Lumber, trim and framing offcuts","Flooring: carpet, laminate, hardwood, and tile if quantity is flagged",
    "Cabinets, countertops and fixtures","Doors, windows and siding","Packaging, pallets and general site waste"]),
  ("What does not, ever",None,None,
   ["Liquid paint, stains, solvents, thinners and adhesives","Fuel, oil and propane","Asbestos-containing material",
    "Treated wood in some disposal streams, so flag it","Anything leaking or of unknown contents"]),
  ("Dumpster or hauler for a renovation?",
   "If debris accumulates over more than about three days, a container is usually cheaper. If it arrives in bursts, scheduled pickups usually win because you only pay for what leaves.",
   "For contractors running several sites at once, scheduled pickups almost always beat a container per job.",None),
 ],
 "takeaway":"Flag heavy material so it is quoted by weight, and test before you disturb anything in a pre-1980 building. Those two steps prevent both of the expensive surprises in renovation disposal.",
 "related":["junk-removal-vs-dumpster-rental","what-junk-removal-companies-will-not-take","shed-and-fence-removal-after-a-storm"],
},
]

POSTS += [
{
 "slug":"downsizing-checklist-for-seniors","date":"2026-08-25","mt":"Downsizing Checklist for Seniors",
 "title":"Downsizing a Home: A Checklist That Respects What Matters",
 "desc":"A realistic plan for moving from a long-held family home into something smaller, without the weekend that ends in an argument.",
 "read":"6 min",
 "intro":[
  "Downsizing after thirty or forty years in one house is not a decluttering project. It is a series of decisions about a life, compressed into a few weeks because a closing date says so.",
  "The families who get through it well are not the ruthless ones. They are the ones who started earlier and made fewer decisions per day."],
 "sections":[
  ("Start with the new floor plan, not the old house","Measure the new place first. Know exactly how many rooms, how much closet space and how much storage there is.",
   "This converts an emotional question into a practical one. The dining set does not fit is a fact. The dining set has to go is an argument.",None),
  ("Three months, not three weekends","Roughly a room a week is sustainable. Three days of solid sorting is not, and it is how people either give up or throw out things they later want back.",
   "Start with the rooms that carry the least meaning: garage, linen closet, spare bedroom. Leave the personal rooms until last, when the decisions have become easier to make.",None),
  ("Photograph before you let go","Many attachments are to the memory rather than the object. A good photograph of the workbench, the Christmas decorations, the kids' height marks on the door frame keeps the memory without the cubic feet.",
   "This one suggestion does more to unstick a downsizing than any other.",None),
  ("Let the family claim things properly","Have each person privately list a small number of items that matter to them, then compare lists.",
   "The lists usually barely overlap, because people want different things for different reasons. It turns a general argument into two or three specific conversations.",None),
  ("Be realistic about resale value",None,None,
   ["<strong>Usually worth less than hoped:</strong> formal china, collectible plates, most furniture from the seventies and eighties, encyclopedias, most pianos.",
    "<strong>Often worth more than assumed:</strong> mid-century furniture, hand tools, certain costume jewellery, vinyl records, cameras, militaria, quality cast iron.",
    "If there is a lot of either category, an appraiser costs far less than what gets thrown away without one."]),
  ("Do not move boxes you have not opened",
   "Anything that has been sealed in a garage or attic unopened for years should be opened and sorted before it moves, not after.",
   "Moving an unopened box to a smaller home just relocates the decision and consumes space you do not have.",None),
  ("Book the clearing before you need it","The last pass has to happen between the move and the closing, which is a narrow and busy window.",
   "Book it as soon as you have the dates rather than in the week itself.",None),
 ],
 "takeaway":"Measure the new place first, work a room a week over months rather than days, and photograph the things you cannot keep. The deadline is the only part you cannot control.",
 "related":["estate-cleanout-checklist","clearing-a-house-before-selling","garage-cleanout-in-a-weekend"],
},
{
 "slug":"helping-a-family-member-with-hoarding","date":"2026-08-18","mt":"Helping a Family Member With Hoarding",
 "title":"Helping a Family Member Whose House Has Become Unmanageable",
 "desc":"What actually helps, what makes it worse, and where junk removal fits. Written by people who do the hauling side of these jobs.",
 "read":"6 min",
 "intro":[
  "We get called by families, usually adult children, usually after something has forced the issue: a fall, a code enforcement letter, a landlord.",
  "We do the hauling. We are not clinicians. But we have been in a lot of these houses, and there are patterns in what works and what backfires badly."],
 "sections":[
  ("The surprise clean-out almost always backfires","The instinct is to arrange everything while the person is away and present a cleared house as a relief.",
   "It reliably produces acute distress, it destroys trust, and the accumulation typically returns faster than before. Whatever the pressure, do not do this to someone.",None),
  ("It is usually not about the objects","Hoarding disorder is a recognised mental health condition and it responds to treatment. It is not laziness and it is not a cleaning problem.",
   "A house cleared without the underlying condition being addressed fills again. That is not a failure of effort, it is what happens when only the symptom is treated.",None),
  ("Start by asking what they want to change",
   "Not what you want changed. Almost everyone in this situation wants something different: to use the kitchen, to have a grandchild visit, to get the landlord off their back.",
   "Working toward a goal they named is the difference between help and an assault on their home.",None),
  ("Go slowly and let them hold the veto","Room by room, session by session, with the person deciding. Nothing leaves without agreement.",
   "It is slower. It is also the only version that tends to hold.",None),
  ("Know the line between junk removal and remediation","This is the practical part, and it determines who you should be calling.",
   "Heavy accumulation of ordinary household material is junk removal: volume, sorting, carrying, disposal. Human or animal waste, decomposition, serious mould or an active infestation is biohazard remediation and needs a licensed contractor. Ask any company directly which one they are. A company that claims both without licensing is one to avoid.",None),
  ("Get professional support involved",
   "A therapist experienced with hoarding disorder, or a professional organiser trained in it, changes outcomes more than any amount of hauling.",
   "The International OCD Foundation maintains resources and directories for hoarding specifically, and it is a better starting point than searching generally.",None),
  ("If there is a deadline you cannot move","Sometimes there genuinely is: an eviction, a condemnation notice, a hospital discharge that needs a safe home.",
   "In that case be honest with the person about the deadline rather than hiding it, and get as much of their agency into the process as the timeline allows. Even choosing the order of rooms helps.",None),
 ],
 "takeaway":"Never clear the house as a surprise. Work toward a goal the person named, go at their pace, and know whether you need a junk removal crew or a licensed remediation contractor before you call anyone.",
 "related":["estate-cleanout-checklist","downsizing-checklist-for-seniors","garage-cleanout-in-a-weekend"],
},
{
 "slug":"preparing-for-a-junk-removal-appointment","date":"2026-08-11","mt":"How to Prepare for a Junk Removal Visit",
 "title":"How to Prepare for a Junk Removal Appointment (and Pay Less)",
 "desc":"Fifteen minutes of preparation gets you a faster job, an accurate quote and no unpleasant surprises when the truck arrives.",
 "read":"4 min",
 "intro":[
  "Most of the friction in this business comes from things that could have been sorted out before the truck left the yard.",
  "None of this is complicated and all of it saves you money."],
 "sections":[
  ("Take photos before you call","Four or five shots from different angles. Include the whole pile, anything unusually heavy, and the route the crew will use to get it out.",
   "Photos turn a guess into a quote that holds. A description of a garage is optimistic from everybody, every time.",None),
  ("Pull out anything hazardous","Do this before anyone arrives. No hauler can legally take these, and discovering them at quote time wastes everybody's time:",None,
   ["Liquid paint, stain, solvent and thinner","Gasoline, oil and fuel cans","Propane tanks including small camping cylinders",
    "Pesticides, herbicides and pool chemicals","Car and marine batteries","Ammunition and flares","Anything unlabelled or leaking"]),
  ("Separate what stays","Tape, a sheet, a sign, or just show the crew. The single most expensive mistake in this business is something being taken that was meant to stay.",
   "If you will not be there, mark it clearly rather than relying on a verbal description.",None),
  ("Tell them about access, honestly",None,None,
   ["Which floor, and whether there is a working elevator","Gate codes, garage codes, lockbox details",
    "Narrow gates, low branches, soft ground on a long driveway","Where the truck can legally park",
    "HOA rules that affect timing or approach"]),
  ("Mention the awkward items specifically","Pianos, pool tables, safes, hot tubs, treadmills, large safes and anything bolted down all change the crew size.",
   "Mentioning them when you book means the right number of people arrive. Not mentioning them means a return visit.",None),
  ("Know what you are agreeing to",
   "Ask three things before anything is loaded: is this the final price or an estimate, is there anything in the pile you cannot take, and do you sweep up.",
   "A straight operator answers all three without hesitating.",None),
 ],
 "takeaway":"Photos before you call, hazardous material pulled out, and what stays clearly marked. Fifteen minutes of preparation removes almost every reason a junk removal job goes wrong.",
 "related":["what-junk-removal-companies-will-not-take","how-much-does-junk-removal-cost-in-orlando","garage-cleanout-in-a-weekend"],
},
{
 "slug":"what-broom-clean-actually-means","date":"2026-08-04","mt":"What Broom Clean Actually Means",
 "title":"What Broom Clean Actually Means in a Lease or a Contract",
 "desc":"The phrase appears in leases, closings and work orders and almost nobody defines it. Here is what it does and does not cover.",
 "read":"4 min",
 "intro":[
  "Broom clean appears in residential leases, commercial lease surrenders, real estate contracts and property management work orders, and it is almost never defined in the document.",
  "That ambiguity is where deposit disputes come from. Here is the generally accepted meaning and, more usefully, where the arguments actually happen."],
 "sections":[
  ("What it generally means",None,None,
   ["All personal property and rubbish removed","Floors swept, or vacuumed where carpeted",
    "Surfaces wiped free of loose debris","Appliances emptied","No items left in garage, attic, shed or yard",
    "Nothing that requires removal by the next party"]),
  ("What it generally does not mean",None,None,
   ["Deep cleaning or professional cleaning","Carpet shampooing or steam cleaning",
    "Scrubbing grout, ovens or bathrooms to a spotless standard","Repainting or patching",
    "Repairing damage of any kind","Removing stains, scuffs or marks"]),
  ("Where the argument actually happens","Three places, consistently.",
   "The garage, which the departing party often does not consider part of the property. The yard, same reasoning. And normal wear and tear, where one side sees a scuff and the other sees damage.",None),
  ("If you are the one leaving","Photograph everything after you clear it, with timestamps. Include the garage, the attic hatch, the shed and the yard.",
   "A complete photo set at handover settles almost every deposit dispute before it starts, and costs you ten minutes.",None),
  ("If you are the landlord or manager","Define it in the lease rather than relying on the phrase. A short list of what is expected removes the argument entirely.",
   "And photograph the unit at both ends of the tenancy. Move-in condition is half the evidence and it is the half people forget.",None),
  ("For commercial lease surrender","Be careful, because commercial leases often require far more than broom clean. Restoration clauses can require removing partitions, restoring flooring, repainting and reinstating the original layout.",
   "Read the actual surrender clause before you budget. Broom clean and full restoration are different jobs by an order of magnitude.",None),
 ],
 "takeaway":"Broom clean means empty and swept, not cleaned. Photograph everything at handover, and if you are writing the lease, define the term instead of relying on it.",
 "related":["rental-turnover-cleanouts","moving-out-of-a-lake-nona-apartment","how-much-does-junk-removal-cost-in-orlando"],
},
{
 "slug":"getting-rid-of-old-exercise-equipment","date":"2026-07-28","mt":"Getting Rid of Old Exercise Equipment",
 "title":"Getting Rid of a Treadmill or Home Gym Without Wrecking the Doorframe",
 "desc":"Why home gym equipment is harder to remove than it looks, what it is actually worth, and the safe way out.",
 "read":"4 min",
 "intro":[
  "Home gym equipment has a predictable life cycle: bought with enthusiasm, used for a few months, then it becomes the most expensive clothes rail in the house.",
  "Getting rid of it is harder than getting it in, for one specific reason."],
 "sections":[
  ("It was assembled in the room it is in","That is the whole problem. Most treadmills, ellipticals and home gyms arrive as a flat box and get built where they stand.",
   "They do not go back out through the door in one piece, and trying to force one is how doorframes get destroyed and backs get hurt.",None),
  ("They are heavier than they look","A motorised treadmill is typically two hundred to three hundred pounds, and almost all of that weight is in the motor at one end.",
   "That unbalanced weight is what makes stairs genuinely dangerous. This is a three-person job, not a two-person job with optimism.",None),
  ("What it is actually worth","Be realistic. The used market for home cardio equipment is poor, because everyone who wants one already has one gathering dust.",
   "Working equipment from a recognised brand has some value. Anything not working has none, and listing it for months while it sits in the spare room costs you the room.",None),
  ("Donation is possible but limited","Some charities and community gyms take working cardio equipment. None of them take broken equipment, and most cannot collect something that needs dismantling first.",
   "Call before you promise it to anyone.",None),
  ("Free weights are a different problem","Plates and dumbbells are dense rather than bulky, so they are priced by weight rather than space, and they are one of the few items with a genuine used market.",
   "Weights actually do sell. Cardio equipment mostly does not.",None),
  ("If you are moving it yourself",None,None,
   ["Unplug it and let it cool if it has been running","Fold and lock the deck if it folds, and check the lock holds",
    "Remove what unbolts, especially the console and uprights","Three people minimum on stairs, with one below and two above",
    "Pad the doorframes before, not after, the first impact"]),
 ],
 "takeaway":"It was built in the room, so it usually has to come apart to leave. Working equipment may be worth donating, broken equipment is not worth listing, and stairs need three people.",
 "related":["how-to-get-rid-of-a-couch","garage-cleanout-in-a-weekend","preparing-for-a-junk-removal-appointment"],
},
{
 "slug":"moving-boxes-and-packing-waste","date":"2026-07-21","mt":"What to Do With Moving Boxes",
 "title":"What to Do With the Mountain of Cardboard After a Move",
 "desc":"A single move generates a startling volume of cardboard. Here is how to get rid of it without annoying your neighbours.",
 "read":"4 min",
 "intro":[
  "Nobody plans for the cardboard. You plan for the furniture, the utilities and the cleaning, and then the move ends and there is a wall of flattened boxes in the garage.",
  "Cardboard is at least one of the easier problems, because it is genuinely recyclable and genuinely wanted."],
 "sections":[
  ("Flatten everything first","This is not optional advice, it is the difference between one manageable stack and a garage you cannot walk through.",
   "Flattened cardboard compresses to a fraction of its assembled volume, which matters whether you are recycling it, storing it or paying someone to haul it.",None),
  ("Pass it on before you recycle it","Moving boxes have a second life and people actively want them. Local buy-nothing groups, neighbourhood apps and marketplace listings clear a stack of good boxes within a day, usually free.",
   "This is the best outcome: no disposal cost, no processing energy, and somebody else does not buy new boxes.",None),
  ("Check your complex before you stack it","If you are in an apartment, find out whether there is a dedicated cardboard area before you assume there is.",
   "A stack beside a dumpster in a complex that has a cardboard area is a violation rather than a recycling attempt, and in many complexes the removal cost gets billed to your unit.",None),
  ("Curbside recycling has limits","Residential recycling collection generally takes flattened cardboard, but there are usually limits on volume per collection and on how it is presented.",
   "A full move's worth will not go out in one week. Spread it over several collections or find another route.",None),
  ("What is not recyclable",None,None,
   ["Packing tape, which should be pulled off where practical","Styrofoam and packing peanuts, which most curbside programs refuse",
    "Bubble wrap and plastic film, which jam sorting equipment","Wax-coated or heavily soiled cardboard",
    "Boxes that got wet and stayed wet"]),
  ("When it is worth paying someone","If you are clearing a whole move's worth at once, if you have furniture going in the same trip, or if you are in a complex with nowhere to put it.",
   "Cardboard compresses well, which usually works in your favour on a volume-priced quote.",None),
 ],
 "takeaway":"Flatten it, offer it to someone moving next week, and check your complex's rules before stacking anything beside a dumpster.",
 "related":["moving-out-of-a-lake-nona-apartment","where-does-your-junk-actually-go","rental-turnover-cleanouts"],
},
]
